
<div class="param-tip">
            <div class="title"><?php echo $msg; ?></div>
            <div class = 'auto-tit'><a href="<?php echo $back_url; ?>"><span id="jumpTo"></span>秒后自动跳转</a></div>
        </div>



<script type="text/javascript">
    function countDown(secs,surl){

         var jumpTo = document.getElementById('jumpTo');
         jumpTo.innerHTML=secs;
         if(--secs>0){
             setTimeout("countDown("+secs+",'"+surl+"')",1000);
             }
         else{
             location.href=surl;
         }
     }

     countDown('<?php echo $sec; ?>', '<?php echo $back_url; ?>');
</script>