<?php
return [
    'game' => [
        'rule_type' => [
            1 => '第一球',
            2 => '第二球',
            3 => '第三球',
            4 => '第四球',
            5 => '第五球',
            6 => '总和',
            7 => '冠亚军和',
            8 => '冠军',
            9 => '亚军',
            10 => '第三名',
            11 => '第四名',
            12 => '第五名',
            13 => '第六名',
            14 => '第七名',
            15 => '第八名',
            16 => '第九名',
            17 => '第十名',
            18 => '第1球',
            19 => '第2球',
            20 => '第3球',
            21 => '第4球',
            22 => '第5球',
            23 => '第6球',
            24 => '第7球',
            25 => '第8球',
            26 => '任选一',
            27 => '任选二',
            28 => '任选三',
            29 => '任选四',
            30 => '任选五',
            31 => '任选六',
            32 => '任选七',
            33 => '任选八',
            34 => '前二组选',
            35 => '前二直选',
            36 => '前三组选',
            37 => '前三直选',
            38 => '和值',
            39 => '三同号通选',
            40 => '三同号单选',
            41 => '三不同号',
            42 => '三连号通选',
            43 => '二同号复选',
            44 => '二同号单选',
            45 => '二不同号'
        ],
        'rule_base_type' => [
            0 => '0',
            1 => '1',
            2 => '2',
            3 => '3',
            4 => '4',
            5 => '5',
            6 => '6',
            7 => '7',
            8 => '8',
            9 => '9',
            10 => '大',
            11 => '小',
            12 => '单',
            13 => '双',
            14 => '龙',
            15 => '虎',
            16 => '和',
            17 => '10',
            18 => '冠亚大',
            19 => '冠亚小',
            20 => '冠亚单',
            21 => '冠亚双',
            22 => '尾大',
            23 => '尾小',
            24 => '极大',
            25 => '极小',
            26 => 10,
            27 => 11,
            28 => 12,
            29 => 13,
            30 => 14,
            31 => 15,
            32 => 16,
            33 => 17,
            34 => 18,
            35 => 19,
            36 => 20,
            37 => 21,
            38 => 22,
            39 => 23,
            40 => 24,
            41 => 25,
            42 => 26,
            43 => 27,
            44 =>'大单',
            45 =>'大双',
            46 =>'小单',
            47 =>'小双',
            48 =>'龙',
            49 =>'虎',
            50 => 28,
            51 => 29,
            52 => 30,
            53 => '和'
        ],
        'rule_size_big' => [10, 11, 12, 13, 22, 23, 24, 25,44,45,46,47,48,49,53],    // 样式，大球
        'rule_size_shape' => [14, 15],  // 样式，方形
        'rule_te' => [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
        '11xuan5' => [17, 18, 19, 20],
        'kuai3' => [14, 15, 16],
        'openConf' => [
            'openCai' => [
                'token' => 'C31083FA6A99166B',
                'mainDomain' => 'http://z.apiplus.net',
                'backupDomain' => 'http://z.apiplus.net',
                'format' => 'json',
                'code' => [
                    '1' => 'cqssc',
                ],
            ],
            'anotherCai' => [
                'token' => 'C31083FA6A99166B',
                'mainDomain' => 'http://d.apiplus.net',
                'backupDomain' => 'http://z.apiplus.net',
                'format' => 'json',
            ],
        ],
        //彩种图标
        'gameImg' => [
            1 => 'img/game-ssc.png',
            2 => 'img/game-pcegg.png',
            3 => 'img/ship.png',
            4 => 'img/game-happy10.png',
            5 => 'img/game-pk10.png',
            6 => 'img/cakeno.png',
            7 => 'img/kuai3.png',
            8 => 'img/kuai3.png',
            9 => 'img/kuai3.png',
            10 => 'img/11xuan5-guangdong.png',
            11 => 'img/11xuan5-zhejiang.png',
            12 => 'img/11xuan5-sandong.png',
            13 => 'img/11xuan5-liaoning.png',
            14 => 'img/kuai3.png',
            15 => 'img/kuai3.png',
            16 => 'img/kuai3.png',
            17 => 'img/11xuan5-guangdong.png',
            18 => 'img/11xuan5-zhejiang.png',
            19 => 'img/11xuan5-sandong.png',
            20 => 'img/11xuan5-liaoning.png',
            21 => 'img/game-txffc.png'
        ],
    ],
    'bank' => [
        0 => '中国农业银行',
        1 => '中国建设银行',
        2 => '中国银行',
        3 => '中国工商银行',
        4 => '中国邮政储蓄银行',
        5 => '招商银行',
        6 => '中国光大银行',
        7 => '交通银行',
        8 => '中国民生银行',
        9 => '兴业银行',
        10 => '广发银行',
        11 => '平安银行',
        12 => '浦发银行',
        13 => '中信银行',
    ],
    'bank_code' => [
            0 => 'b001',
            1 => 'b002',
            2 => 'b003',
            3 => 'b004',
            4 => 'b005',
            5 => 'b006',
            6 => 'b007',
            7 => 'b008',
            8 => 'b010',
            9 => 'b011',
            10 => 'b012',
            11 => 'b013',
            12 => 'b014',
            13 => 'b015',
        ],
    'type' => [
        1 => '充值',
        3 => '开奖结算',
        5 => '提现',
        7 => '投注',
        9 => '系统赠送',
        11 => '下级回水',
        13 => '个人回水',
        15 => '退款'
    ],

    //快乐飞艇数字颜色配置
    'color' => [
        1 => 'sicon-yellow',
        2 => 'sicon-dblue',
        3 => 'sicon-dgray',
        4 => 'sicon-orange',
        5 => 'sicon-blue',
        6 => 'sicon-purple',
        7 => 'sicon-gray',
        8 => 'sicon-red',
        9 => 'sicon-dred',
        10 => 'sicon-green',
    ],
    //彩种数字风格
    'style' => [
        1 => 'circle',
        2 => 'circle',
        3 => 'square',
        4 => 'circle',
        5 => 'square',
        6 => 'circle',
        7 => 'circle',
        8 => 'circle',
        9 => 'circle',
        10 => 'circle',
        11 => 'circle',
        12 => 'circle',
        13 => 'circle',
        14 => 'circle',
        15 => 'circle',
        16 => 'circle',
        17 => 'circle',
        18 => 'circle',
        19 => 'circle',
        20 => 'circle',
    ],

    //菜单图标样式
    'menu' => [
        'order' => 'actual',
        'abnormal' => 'throw',
        'history' => 'history',
        'forms' => 'financail',
        'search' => 'chart',
        'user' => 'user',
        'agent' => 'agent',
        'system' => 'system',
        'admin' => 'backstage',
        'log' => 'log',
        'money' => 'withdrawal'
    ],

    // 支付配置
    // 'payment' => [
    //     'austpay' => [
    //         'merchant_id' => 'MIDTES1',  // 商户id
    //         'password' => '325sdfjsDHFKL',
    //         'site_id' => '2000065',  // 站点id
    //         'api_url' => 'http://zf.dyyjk.com/api3.php', // 扫码API url
    //         'return_url' => 'http://dazhongcai.vip/pay/aust', // 同步跳转url
    //         'notify_url' => 'http://dazhongcai.vip/pay/austcb',  // 异步通知url
    //         'payType' => [  // 支付方式对应
    //             5 => 1,
    //             1 => 2,
    //             3 => 3
    //         ],
    //         'with_url' => 'http://zf.dyyjk.com/disburse.php',   // 代充值api接口   提现
    //         'sign_string' => 'Ya9px89AsyMM7omUt7KN64kKdA8gLyYIBbXXkQqwgGKDuems2hqrJrSJKqJMoF2I',   // 密钥
    //         'bank_code' => [
    //             0 => 'b001',
    //             1 => 'b002',
    //             2 => 'b003',
    //             3 => 'b004',
    //             4 => 'b005',
    //             5 => 'b006',
    //             6 => 'b007',
    //             7 => 'b008',
    //             8 => 'b010',
    //             9 => 'b011',
    //             10 => 'b012',
    //             11 => 'b013',
    //             12 => 'b014',
    //             13 => 'b015',
    //         ],
    //         'log' => '../app/logs/austpay.log'
    //     ],
    // ],

    'newpayment' => [
        'pay_type' => 80002, //pay_type in [80001, 80002, 80003, 80004]
        'total_amount' => 100, //单位为分 填写100则为1元
        'subject' => 'dk',
        'out_trade_no' => time(),//商户订单号,商户随机生成
        'body' => 'dk',
        'return_url' => 'https://wx.sfk92.cn/pay/aust',
        'notify_url' => 'https://wx.sfk92.cn/pay/austcb',
        'bank_code' => '',
        'type' => 2,
        'api_url' =>'https://api.rn3.cc/gateway/v1/trade',
        'bank_code' => [
                0 => 'b001',
                1 => 'b002',
                2 => 'b003',
                3 => 'b004',
                4 => 'b005',
                5 => 'b006',
                6 => 'b007',
                7 => 'b008',
                8 => 'b009',
                9 => 'b010',
                10 => 'b011',
                11 => 'b012',
                12 => 'b013',
                13 => 'b014',
                14 => 'b015',
            ],
         ],

    'order_draw' => [
        1 => '中奖',
        3 => '未中奖',
        5 => '未开奖'
    ],

    //充值方式  1.'扫码支付',3.银行卡汇款
    'payType' => [
        1 => [
                1 => '微信入款',
                3 => 'QQ钱包入款',
                5 => '支付宝入款',
                7 => '网银入款',
                9 => '支付宝收款码',
                11 => '微信收款码',
                13 => '银联扫码',
                17 => '京东金融' ,
                19 => '百度钱包'
            ],
        2=>[15=>'银行卡汇款'],
    ],
    'rechargebank' =>
    [
        0 => '中国农业银行',
        1 => '中国建设银行',
        2 => '中国银行',
        3 => '中国工商银行',
        4 => '中国邮政储蓄银行',
        5 => '招商银行',
        6 => '中国光大银行',
        7 => '交通银行',
        8 => '中国民生银行',
        9 => '兴业银行',
        10 => '广发银行',
        11 => '平安银行',
        12 => '浦发银行',
        13 => '中信银行',
    ],

    //支付方式icon图标
    'payIcon' => [
        1 => 'img/icon/wx-icon.png',
        3 => 'img/icon/qq-icon.png',
        5 => 'img/icon/alipay-icon.png',
        7 => 'img/icon/yl-icon.png',
        9 => 'img/icon/alipay-icon.png',
        11 => 'img/icon/wx-icon.png',
        13 => 'img/icon/yl-icon.png',
        17 => 'img/icon/jd-icon.png',
        19 => 'img/icon/baidu-icon.png',
    ]

];
