 <style>
    .layui-layer-content{
       color: #fff!important;
    }
</style>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>网易彩票</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="/css/jquery.cxcalendar.css">

    <script src="/js/jquery-2.2.3.min.js"></script>
    <script src="/js/jquery.cxcalendar.js"></script>
    <script src="/js/powerange.min.js"></script>
    <script src="/js/range.js"></script>
    <script src="/js/main.js"></script>
    <script src="/js/jquery.form.js"></script>
    <script src="/js/layer/layer.js"></script>
    <script src="/js/jquery.validate.js"></script>
    <script src="/js/uploadPreview.js"></script>
    <script src="/js/api.js"></script>
    <script type="text/javascript">
    jQuery.browser={};(function(){jQuery.browser.msie=false; jQuery.browser.version=0;if(navigator.userAgent.match(/MSIE ([0-9]+)./)){ jQuery.browser.msie=true;jQuery.browser.version=RegExp.$1;}})();
    </script>
</head>
<body>
   <div class="login-body">
        <form action="dologin">
        <div class="login-panel">
            <div class="head-logo">
                <img src="/img/logo.png" />
            </div>
            <div class="item">
                <input type="text" placeholder="用户名" class="user" name= 'user' value = ''>
            </div>
            <div class="item">
                <input type="password" placeholder="密码" class="pwd" name = 'pwd' value = ''>
            </div>
            <div class="item mt10">
                <input type="text" placeholder="验证码" class="chk" name = 'captcha' value = ''>
                <span class="chk-code">
                <img src="/index/captcha" id="checkpic" onclick="changing();" />
                </span>
            </div>
            <button class="login-btn" type = 'submit'>登录</button>
        </div>
        <form>
    </div>
</body>
</html>
    <script type="text/javascript">
    function reload()
    {
        location.href = '';
    }
   $('form').submit(function() {
        $(this).ajaxSubmit({
            dataType: 'json',
            type: "POST",
            success: function (msgObj) {
                    if (msgObj.code == 500) {
                        layer.msg(msgObj.msg);
                        return false;
                    }
                    window.location.href = msgObj.data.url;
            },
            error: function(e){
                layer.msg("<h2>登录失败请重新登录</h2>");
            },
        });
        return false;
    });

    function changing(){
        document.getElementById('checkpic').src="/index/captcha?"+Math.random();
    }
</script>

