
    <div class="wx-result-body">
        <?php $this->partial("shared/usertop"); ?>
        <div class="result-tit">
            充值申请提交成功，请在24小时内完成支付
        </div>
        <ul class="input-panel wx-panel">
            <li class="item flex">
                <label>订单号</label>
                <span class="flex1 on">
                    2201704121136284810       
                </span>
            </li>
            <li class="item flex">
                <label>支付平台</label>
                <span class="flex1 on">
                    <!--<i class="con wallet-pay"></i> 微信-->
                     <i class="con z-pay"></i> 支付宝           
                </span>
            </li>
            <li class="item flex">
                <label>充值金额</label>
                <span class="flex1 red">
                    100       
                </span>
            </li>
        </ul>
        <div class="btn-center">
            <input type="submit" value="提交" class="btn">
        </div>
    </div>