 <div class="code-body">
        <div class="tip flex">
            <span class="name flex1"><?php echo $uName ?></span>
            <span class="money"><i class="d"></i><?php echo $money ?></span>
            <span class="h-money unsee"><i class="d"></i>隐藏金额</span>
        </div>
        <div class="tit">支付宝扫一扫向我支付</div>
        <div class="code-img">
            <img src="img/code.png" />
        </div>
        <div class="m-val">￥<?php echo $moneyR ?></div>