<?php
    $bet = $js = $betdate = $js2 = $js3 = $js4 = $js5 = '';
    if (isset($_GET['limit'])) {
        $urlLimit = $_GET['limit'];
        $js = '$("#limit").val('.$urlLimit.');';
        if (!in_array($_GET['limit'], $perpage))
            $urlLimit = current($perpage);
    }
    if (!empty($_GET['page'])) {
        if (is_numeric($_GET['page'])) {
            $js4 = '$("#page").val('.$_GET['page'].');';
            $page = $_GET['page'];
        }
        else {
            $js4 = '$("#page").val(1);';
            $page =1;
        }
    }

    if(!empty($type)) {
        if (isset($_GET['type']) && $_GET['type'] !=0 ) {
            $js= '$("#bet_type").val('.$_GET['type'].');';
            if (!empty($type))
                $bet = $type[$_GET['type']];
        } else
            $bet = current($type);
    }

    if(!empty($date)) {
        if (isset($_GET['date'])) {
            $js2= '$("#date").val('.$_GET['date'].');';
            if (!empty($date))
                $betdate = $_GET['date'];
        } else
            $betdate = current($date);
    }
?>
<div class="chart-query-body container">
        <div class="top-title">
            <i class="chart-red"></i> <em class="tit">订单查询</em>
        </div>
         <form  action="/search/index" method="get">
        <div class="search-box">
            <div class="search-down">彩票类型:
                <div class="select-box">
                    <select class="list" name = "type" id="bet_type">
                    <?php if(!empty($type)) : foreach ($type as $key => $value) : ?>
                        <option value="<?=$key?>"><em class="txt"><?=$value?></em></option>
                    <?php endforeach; endif;?>
                    </select>
                    <em class="txt"><?=$bet?></em>
                    <i class="i-arrow"></i>
                </div>
&nbsp
            <input type="radio" class="radio" name="radio" value=5 <?php if($this->request->get('radio') == 5) echo "checked" ?>> 交易号:
            <div class="date-box" >
                <input type='text' name='sn' id='sn' value="<?=!empty($_GET['sn']) ? $_GET['sn'] : '' ?>">
            </div>用户名:
                <div class="date-box" >
                    <input type='text' name='nick' id='nick' value="<?=!empty($_GET['nick']) ? $_GET['nick'] : '' ?>">
                </div>
    </div>

        <input type="hidden" name="type" value="<?=!empty($_GET['type']) ? $_GET['type'] : '' ?>">
        <input type="hidden" name="uid" value="<?=!empty($_GET['uid']) ? $_GET['uid'] : '' ?>">
            <div class="radio-group">
                <input type="radio" class="radio" name="radio" value=1 <?php if($this->request->get('radio') == 1) echo "checked" ?>> 按期数:
                <div class="select-box">
                    <select class="list" name="date" id="date">
                    <?php  if(!empty($date)) :  foreach ($date as $key=>$value): ?>
                        <option value="<?=$value?>"><?=$value?></option>
                    <?php endforeach; endif;?>
                    </select>
                    <em class="txt"><?=!empty($betdate) ? $betdate : '期'?></em>
                    <i class="i-arrow"></i>
                </div>
                <input type="radio" class="radio" name="radio" value=3 <?php if($this->request->get('radio') == 3) echo "checked" ?>> 按日期:
                <div class="date-box">
                    <input type="text" name="startTime"  id="start_time" value="<?=!empty($_GET['startTime']) ? $_GET['startTime'] : '' ?>">
                    <i class="date-icon"></i>
                </div>
                <label class="connet-line"></label>
                <div class="date-box" >
                    <input type="text" name="endTime" id="end_time" value="<?=!empty($_GET['endTime']) ? $_GET['endTime'] : ''  ?>">
                    <i class="date-icon"></i>
                </div>
                <button class="search-btn" id="sub">查询</button>
            </div>
            </form>

        </div>
        <div class="table-box">
            <table class="main-table" cellpadding="0" cellspacing="0">
                <thead>
                    <tr>
                        <th>交易号码</th>
                        <th>账号</th>
                        <th>彩种</th>
                        <th>期号</th>
                        <th>状态</th>
                        <th>玩法</th>
                        <th>下注号码</th>
                        <th>投注金额</th>
                        <th>派彩金额</th>
                        <th>奖金/返点</th>
                        <th>归属代理</th>
                        <th>下注时间</th>
                    </tr>
                </thead>
                <tbody>
                <?php if (empty($info['total'])) {?>
                   <tr class="null">
                        <td colspan="11">暂无数据！</td>
                    </tr>
                    <?php } else { foreach ($info['list'] as $value) : $num = explode('-', $value['bo_content']) ?>
                    <tr>
                        <td><?=$value['bo_sn']?></td>
                        <td><a style="color:#45a6d9" href="/user/index?value=<?=$value['u_name']?>&condition=1" ><?=$value['u_name']?></a></td>
                        <td><?=$type[$value['bet_id']]?></td>
                        <td><?=$value['bo_issue']?></td>
                        <td><?php if($value['bo_status'] ==5 ){echo "已撤销";}else{
                            if($value['bo_draw_result'] ==1 ){echo "中奖";}elseif ($value['bo_draw_result'] ==3 ) {
                                echo "未中奖";
                            }else{
                                echo "未开奖";
                            }
                            } ?></td>
                         <?php if(!in_array($value['bet_id'],[14,15,16,17,18,19,20])) { ?>
                        <td><?=$value['bo_played_name']?></td>
                        <td>
                             <span class="bett-size red"><?=$game['rule_type'][$num[0]]?>
                            <i class="circle mr5"><?=$game['rule_base_type'][$num[1]]?></i>
                            </span>
                            <?php } else {
                                echo '<td class="red">'.$value['bo_played_name'].'</td><td><span class="bett-size red" style="font-size:15px">'.$num[1].'</span>';
                                }?>
                         </td>
                        <td><?=$value['bo_money']?></td>
                        <td><?=$value['bo_bonus']?></td>
                        <td><?=$value['bo_odds']?>/<?=$value['bo_rs_tax']?>%</td>
                        <td><a style="color:#45a6d9" href="/user/index?value=<?=$value['bo_u_name']?>&condition=1" ><?=empty($value['bo_u_name']) ? '-' : $value['bo_u_name']?></a></td>
                        <td><?=date('Y-m-d H:i', $value['bo_created_time'])?></td>

                    </tr>
                       <?php  endforeach;  ?>
                </tbody>
            </table>
        </div>

        <div class="pages">
            <div class="posl">
                共<em class="counts" ><?=$info['total']?></em>条 每页显示
                <div class="select-box line-num">
                    <select class="list" id="limit">
                    <?php foreach ($perpage as $key => $value) : ?>
                        <option value="<?=$key?>"><?=$value?></option>
                    <?php endforeach ?>
                    </select>
                    <em class="txt"><?=!empty($urlLimit) ? $urlLimit : current($perpage); ?></em>
                    <i class="i-arrow"></i>
                </div>条
            </div>
            <div class="switch-box">
                <a class="page-btn mr10" id="left"><i class="left"></i></a> 第
                <div class="select-box line-num">
                    <select class="list" id="page">
                      <?php if(!empty($info['limit'])): for($i=1; $i <= $info['limit']; $i++ ) : ?>
                        <option value="<?=$i?>"><?=$i?></option>
                    <?php endfor; endif; ?>
                    </select>
                    <em class="txt"><?=!empty($page) ? $page : 1?></em>
                    <i class="i-arrow"></i>
                </div>
                共<em id="total"><?=$info['limit']?></em>页
                <a class="page-btn ml10" id="right"><i class="right" ></i></a>
            </div>
        </div>
    <?php }?>
    </div>

<script type="text/javascript">

    $('#start_time').cxCalendar({
        type: 'datetime',
        format:'YYYY-MM-DD HH:mm'
    });
     $('#end_time').cxCalendar({
        type: 'datetime',
        format:'YYYY-MM-DD HH:mm'
    });

    <?php echo $js; echo $js2; echo $js3; echo $js4;?>
   $(function() {
        $('#start_time').attr('disabled',true);
        $('#end_time').attr('disabled',true);
        $('#date').attr('disabled',true);
        var val=$('input:radio[name="radio"]:checked').val();
        if (val ==1) {
                    $('#start_time').attr('disabled',true);
                    $('#end_time').attr('disabled',true);
                    $('#date').attr('disabled',false);
                    $('#sn').attr('disabled', 'disabled');
        }
        if(val == 3) {
                    $('#start_time').attr('disabled',false);
                    $('#end_time').attr('disabled',false);
                    $('#date').attr('disabled','disabled');
                    $('#sn').attr('disabled', 'disabled');
                }
        if(val ==5) {
                    $('#start_time').attr('disabled', 'disabled');
                    $('#end_time').attr('disabled', 'disabled');
                    $('#date').attr('disabled','disabled');
                    $('#sn').attr('disabled', false);
        }
        $('.radio').on('change',function() {
            var val=$('input:radio[name="radio"]:checked').val();
            if (val ==1) {
                    $('#start_time').attr('disabled',true);
                    $('#end_time').attr('disabled',true);
                    $('#date').attr('disabled',false);
                    $('#sn').attr('disabled', 'disabled');
                }
            if(val == 3) {
                    $('#start_time').attr('disabled',false);
                    $('#end_time').attr('disabled',false);
                    $('#date').attr('disabled','disabled');
                    $('#sn').attr('disabled', 'disabled');
                }
            if(val ==5) {
                    $('#start_time').attr('disabled', 'disabled');
                    $('#end_time').attr('disabled', 'disabled');
                    $('#date').attr('disabled','disabled');
                    $('#sn').attr('disabled', false);
                }
        })
        $('#bet_type').on('change', function(){
            var bid = $('#bet_type').val();
            var url = '/search/index?type='+bid;
            location.href = url;
        });
        $('#sub').on('click', function(){
            var val=$('input:radio[name="radio"]:checked').val();
            if (val == undefined && $('#nick').val()=='' ) {
                return false;
            }
            if (val ==3) {
                var start_time = $("input[name='startTime']").val();
                var end_time = $("input[name='endTime']").val();
                if(start_time == '') {
                    layer.msg('开始时间不能为空');
                    return false;
                };
                var start = Date.parse(new Date(start_time));

                if(end_time == '') {
                    layer.msg('结束时间不能为空');
                    return false;
                };
                var end = Date.parse(new Date(end_time));

                if (start > end) {
                    layer.msg('请输入正确时间');
                    return false;
                }
            }
            if (val ==1) {
                val = $('#date').val();
                if (val == null) {
                    layer.msg('期数不能为空');
                    return false;
                }
            }

        })
    })
    </script>