
<div class="team-chart-body">
        <?php $this->partial("shared/usertop"); ?>
        <div class="search-box">
            <div class="date flex">
                <span class="box flex1">
                    <input type="date" value="<?php echo $start ?>" id="startDay" placeholder="请选择日期">
                    <em><?php echo $start?$start:'请选择日期'  ?></em>
                </span>
                <label class="word">至</label>
                <span class="box flex1">
                    <input type="date" value="<?php echo $end ?>" id="endDay" placeholder="请选择日期">
                    <em><?php echo $end?$end:'请选择日期'  ?></em>
                </span>
            </div>

            <input type="submit" value="搜索" class="btn" id="search">
            <div class="options-list">
                <span data-date='1' <?php echo $pame == 1?'class="on"':'' ?>>今日</span>
                <span data-date='2' <?php echo $pame == 2?'class="on"':'' ?>>昨日</span>
                <span data-date='3' <?php echo $pame == 3?'class="on"':'' ?>>本周</span>
                <span data-date='4' <?php echo $pame == 4?'class="on"':'' ?>>上周</span>
                <span data-date='5' <?php echo $pame == 5?'class="on"':'' ?>>本月</span>
                <span data-date='6' <?php echo $pame == 6?'class="on"':'' ?>>上月</span>
                <input type="hidden" name="selectUid" id="selectUid" value="<?php echo $selectUid ?>">
            </div>
        </div>
        <div class="main-table">
            <table>
                <thead>
                    <tr>
                        <th>用户名</th>
                        <th>类型</th>
                        <th>充值</th>
                        <th>提现</th>
                        <th>投注额</th>
                        <th>输赢</th>
                        <?php if($selectUid == $uId){ ?>
                        <th>我的佣金</th>
                        <?php } ?>
                        <th>详情</th>
                    </tr>
                </thead>
                <tbody>
                    <?php for($i=0;$i<count($base);$i++){ ?>
                    <tr id="tbody">
                        <td>
                            <a href="/team/report?uId=<?php echo $base[$i]['u_id']?>"><?php echo $base[$i]['u_name']?></a>
                        </td>
                        <td><?php echo $base[$i]['ua_type']?></td>
                        <td class="red"><?php echo $othorInfo[$i]['ar_team_recharge_money']  ?></td>
                        <td class="red"><?php echo $othorInfo[$i]['ar_team_withdraw_money']  ?></td>
                        <td class="red"><?php echo $othorInfo[$i]['ar_team_bet_money'] + $othorInfo[$i]['ar_my_bet_money']  ?></td>
                        <td class="red"><?php echo sprintf('%.1f', $othorInfo[$i]['ar_team_earn_money']-$othorInfo[$i]['ar_team_bet_money']+$othorInfo[$i]['ar_team_reback_money']+$othorInfo[$i]['ar_team_back_money']+$othorInfo[$i]['ar_my_earn_money'] - $othorInfo[$i]['ar_my_bet_money'] + $othorInfo[$i]['ar_my_reback_money'])?></td>
                        <?php if($selectUid == $uId){ ?>
                        <td class="red"><?php echo $othorInfo[$i]['ar_up_back_money'] ?></td>
                        <?php } ?>
                        <td><i class="right"></i></td>
                    </tr>
                    <tr class="detail-list unsee">
                        <td colspan="8">
                            <ul class="detail clearfix">
                                <li class="flex">
                                    <span class="tit">此级投注</span>
                                    <span class="va flex1" id="mybet"><?php echo $othorInfo[$i]['ar_my_bet_money']?></span>
                                </li>
                                <li class="flex">
                                    <span class="tit">此级盈亏</span>
                                    <span class="va flex1" id="myearn"><?php echo $othorInfo[$i]['ar_my_earn_money'] - $othorInfo[$i]['ar_my_bet_money']+$othorInfo[$i]['ar_my_reback_money']?></span>
                                </li>
                                <li class="flex">
                                    <span class="tit">注册人数</span>
                                    <span class="va flex1" id="widraw"><?php echo $base[$i]['ua_reg_nums'] ?></span>
                                </li>
                                <li class="flex">
                                    <span class="tit">备注<i class="edit-icon" data-uId="<?php echo $base[$i]['u_id']?>"></i></span>
                                    <span class="va flex1" id="memo">(<?php echo $base[$i]['ua_memo'] ?>)</span>
                                </li>
                            </ul>
                        </td>
                    </tr>
                    <?php }?>
                    <tr>
                        <td colspan="2">总计</td>
                        <td class="red" id="total"><?php echo $total['ar_team_recharge_money'] ?></td>
                        <td class="red" id="total"><?php echo $total['ar_team_withdraw_money'] ?></td>
                        <td class="red" id="total"><?php echo $total['ar_team_bet_money'] + $total['ar_my_bet_money'] ?></td>
                        <td class="red" id="total"><?php echo $total['ar_team_earn'] ?></td>
                        <?php if($selectUid == $uId){ ?>
                        <td class="red" id="total"><?php echo $total['ar_team_upback_money'] ?></td>
                        <?php } ?>
                        <td><i class="right"></i></td>
                    </tr>
                    <tr class="detail-list unsee">
                        <td colspan="8">
                            <ul class="detail clearfix">
                                <li class="flex">
                                    <span class="tit">此级团队投注</span>
                                    <span class="va flex1" id="backMoney"><?php echo $total['ar_my_bet_money'] ?></span>
                                </li>
                                <li class="flex">
                                    <span class="tit">此级团队盈亏</span>
                                    <span class="va flex1" id="backMoney"><?php echo $total['ar_team_my_earn'] ?></span>
                                </li>
                                <li class="flex">
                                    <span class="tit">注册人数</span>
                                    <span class="va flex1" id="widraw"><?php echo $totalReg ?></span>
                                </li>
                                <li></li>
                            </ul>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
          <div class="pwd-pop unsee" id="editmemo">
            <div class="row-cells">
              <div class="row-cell flex mt20">
                <div class="row-box_cd">
                  <input type="text" placeholder="请输入备注" class="row-input" />
                </div>
              </div>
            </div>
            <div class="mt20">
              <button class="f-btn f-cancel">取消</button>
              <button class="f-btn f-sure">确定</button>
            </div>
          </div>
    <script type="text/javascript">
    //备注编辑
    var editid = '';
    $('.edit-icon').on('click',function(){
        editid = $(this).attr('data-uId');
        $('.mask').removeClass('unsee');
        $('#editmemo').removeClass('unsee');
        $('.f-sure').on('click',function(){
            $(this).attr('disabled', false).html('修改中');
            var id = editid;
            var info = $('.row-input').val();
            $.ajax({
                    type: "POST",
                    url: "/user/edit",
                    data:{info:info,uId:editid},
                    dataType: "json",
                    success: function(res)
                    {
                        if(res.code == 200)
                        {
                            alert('修改成功');
                            window.location.href = '/team/report';
                            return false;
                        }else{
                            alert('修改失败');
                        }
                    }
                });
            
        })
    })

    $('.f-cancel').on('click',function(){
        $('.mask').addClass('unsee');
        $('#editmemo').addClass('unsee');  
    })
    //快捷搜索
    $(".options-list span").each(function() {
        $(this).click(function() {
            var pame = $(this).attr('data-date');
            var selectUid=$('#selectUid').val(); 
            $(".options-list span").removeClass("on");
            $(this).addClass("on");
            window.location.href = '/team/report?pame='+pame+'&uId='+selectUid;
            });
    //日期处理方法
    function changeTime(time) 
    {
        var Month = time.substring(5,7 );
        var Day = time.substring(8,10);
        var Year = time.substring(0,4);
        return Year + '/' + Month + '/' + Day ;
    }
    //点击日期搜索
   $('#search').click(function(){
        var start = $("#startDay").val();
        var end = $("#endDay").val();
        var selectUid=$('#selectUid').val(); 
        var startDay = changeTime(start);
        var endDay = changeTime(end);
        if(startDay == "//")
        {
             alert("请选择开始日期");return false;
        }
        if(endDay == "//")
        {
             alert("请选择截止日期");return false;
        }
        if(endDay < startDay)
        {
            alert("截止日期不能小于开始日期");return;
        }
        window.location.href = '/team/report?uId='+selectUid+'&startTime='+start+'&endTime='+end;
        });
    });

    </script>