<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
        <?php $this->assets->outputJs() ?>
        <?php $this->assets->outputCss() ?>
        <!-- Optional theme -->
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.min.css">

        <!-- Latest compiled and minified JavaScript -->
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    </head>
    <body>
        <div class="container">
           <div style="margin-bottom:10px;">
               </br></br></br>
            <a href="javascript:;" id="aToday">今天</a>
            <a href="javascript:;" id="aLast7Days">最近3天</a>
            <span class="vs">|</span>
            <a href="javascript:;" id="aRecent7Days">最近一周</a>
            <a href="javascript:;" id="aRecent14Days">最近14天</a>
            <span class="vs">|</span>
            <a href="javascript:;" id="aRecent30Days">最近一月</a>
             <input type="input" id="month_picker" name="month_picker" class="form-control" />
              <!--<a href="javascript:;" id="js_searchBtn" class="btn btn-success">查询</a>-->
               <button type="button" id="js_searchBtn" class="btn-success">查询</button>
              </div>
	<div class="row clearfix">
		<div class="col-md-12 column">
			<table class="table">
				<thead>
					<tr>
						<th>
							总团队人数
						</th>
						<th>
							时间范围内注册人数
						</th>
						<th>
							余额
						</th>
						<th>
							提现
						</th>
                                                <th>
							充值
						</th>
                                                <th>
							中奖金额
						</th>
                                                <th>
							投注金额
						</th>
                                                <th>
							代理返点
						</th>
                                                <th>
							净盈利
						</th>
					</tr>
				</thead>
				<tbody>

					<tr>
						<td>
                                                    <?php echo $num[0]['a_team_nums'] ?>
						</td>
						<td>
                                                    <?php echo $num[0]['a_team_reg_nums'] ?>
						</td>
						<td>
                                                    <?php echo $info['tsd_money'] ?>
						</td>
						<td>
                                                    <?php echo $info['tsd_withdraw'] ?>
						</td>
                                                <td>
                                                    <?php echo $info['tsd_recharge'] ?>
						</td>
						<td>
                                                    <?php echo $info['tsd_pay_bonuses'] ?>
						</td>
                                                <td>
                                                    <?php echo $info['tsd_bet_money'] ?>
						</td>
                                                <td>
                                                    <?php echo $info['tsd_reback_money'] ?>
						</td>
                                                <td>
                                                    <?php echo $info['tsd_earn_money'] ?>
						</td>
					</tr>


				</tbody>
			</table>
		</div>
	</div>
        </div>
            <script type="text/javascript">
            var myDate = new Date();
        var month = parseInt(myDate.getMonth()) + 1;
        var toDay = myDate.getFullYear() + '-' + month + '-' + myDate.getDate();
        var dateRange = new pickerDateRange('month_picker', {
            startDate: toDay,
            endDate: toDay,
            defaultText: ' 至 ',
            theme: 'ta'
        });

        $(function(){
           $('.btn-success').click(function(){
               var month_picker = $("#month_picker").val();
            var arr = month_picker.split(" 至 ");
//            debugger;
            var start_date = arr[0];
            var end_date = arr[1];
            $.ajax({
                    type: "POST",
                    url: "/team/datashow",
                    data:{start_date:start_date, end_date:end_date},
                    dataType: "json",
                    success: function(data){
                             }
                });
           });
       });
        </script>
    </body>
</html>
