<div class="account-centre-body">
<?php $this->partial("shared/usertop"); ?>
<ul class="agent-manage">
    <li class="item">
        <a href="/team/show">
            <i class="team-manage"></i>
            <span class="agent-text">下线总账</span>
        </a>
    </li>
    <li class="item">
        <a href="/user/list">
            <i class="user-list"></i>
            <span class="agent-text">下线列表</span>
        </a>
    </li>
<!--    <li class="item">
        <a href="/agent/add">
            <i class="user-manage"></i>
            <span class="agent-text">注册管理</span>
        </a>
    </li>-->
    <li class="item">
        <a href="/team/table">
            <i class="team-chart"></i>
            <span class="agent-text">下线报表</span>
        </a>
    </li>
</ul>
</div>