<table class="card-info t-format">
    <thead>
        <tr class="head">
            <td>姓名</td>
            <td>银行名称</td>
            <td>出款账号</td>
            <td>省市</td>
            <td>状态</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>陈**</td>
            <td>中国光大银行</td>
            <td>462**********300</td>
            <td>福建泉州</td>
            <td class="state">正常</td>
        </tr>
        <tr>
            <td>陈**</td>
            <td>中国光大银行</td>
            <td>462**********300</td>
            <td>福建泉州</td>
            <td class="state">正常</td>
        </tr>
        <tr>
            <td>陈**</td>
            <td>中国光大银行</td>
            <td>462**********300</td>
            <td>福建泉州</td>
            <td class="state">正常</td>
        </tr>
        <tr>
            <td>陈**</td>
            <td>中国光大银行</td>
            <td>462**********300</td>
            <td>福建泉州</td>
            <td class="state">正常</td>
        </tr>
    </tbody>
    </table>
    <div class="btn-center">
    <input type="submit" value="绑定银行卡" class="btn">
    </div>