<div class="context">
    <!-- <div class="user-view">
        <ul class="list">
            <li class="item">
                <span class="num"><?=$today['tsd_recharge'] ?: 0?></span>
                <span class="tap-text">今日存款总计</span>
            </li>
            <li class="item">
                <span class="num"><?=$today['tsd_withdraw'] ?: 0?></span>
                <span class="tap-text">今日取款总计</span>
            </li>
            <li class="item">
                <span class="num"><?=$today['tsd_earn_money'] ?: 0?></span>
                <span class="tap-text">今日彩票输赢</span>
            </li>
            <li class="item">
                <span class="num"><?=$yestoday['tsd_recharge'] ?: 0?></span>
                <span class="tap-text">昨日存款总计</span>
            </li>
            <li class="item">
                <span class="num"><?=$yestoday['tsd_withdraw'] ?: 0?></span>
                <span class="tap-text">昨日取款总计</span>
            </li>
            <li class="item">
                <span class="num"><?=$yestoday['tsd_earn_money'] ?: 0?></span>
                <span class="tap-text">昨日彩票输赢</span>
            </li>
        </ul>
    </div> -->
</div>