
<div class="my-info-body">
    <?php $this->partial("shared/usertop"); ?>
    <div class="user-view">
            <div class="detail flex">
                <div class="hd flex1">
                    <p class="title">会员账号</p>
                    <p class="name"><?php echo $uName ?></p>
                </div>
                <div class="hd flex1">
                    <p class="title">昵称</p>
                    <p class="name"><?php echo $unick['u_nick'] ?></p>
                </div>
            </div>
        </div>
        <div class="select-title-black">
            <span>
                    <select class="select-p" id="lotteryType">
                        <?php for($i = 0; $i < count($lottery); $i++) { ?>
                        <option value="<?php echo $lottery[$i]['bet_id'] ?>"><?php echo $lottery[$i]['bet_name'] ?></option>
                        <?php } ?>
                    </select>
                    <em>重庆时时彩</em>
                </span>
        </div>
        <table class="t-format">
            <thead>
                <tr class="head">
                    <td>玩法</td>
                    <td>单注最低</td>
                    <td>单注最高</td>
                </tr>
            </thead>
            <tbody id="table">
                <?php for( $i = 0; $i < count($play); $i++) { ?>
                <tr>
                    <td><?php echo $play[$i]; ?></td>
                    <td><?php echo $limit[0]['bet_min']; ?></td>
                    <td><?php echo $limit[0]['bet_max']; ?></td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
<script>
$(document).ready(function () {
             $(".select-p").change(function () {
                var type=$('.select-p option:selected').val();
                $.ajax({
                    type: "POST",
                    url: "freshByType",
                    data:{type:type},
                    dataType: "json",
                    success: function(res)
                    {
                        if(res.code == 200)
                        {
                            var str='';
                            $.each(res.data.play,function(index, n)
                            {
                                str=str+'<tr><td>'+res.data.play[index]+'</td><td>'+res.data.limit[0].bet_min+'</td><td>'+res.data.limit[0].bet_max+'</td></tr>';
                            });
                            $("#table").html(str);
                        }
                    }
                    
                });
             });
         });    
</script>