<?php if($brid==1) { ?>
    <div class="h-auto trend">
        <div class="table-container">
            <table  class="dataTable">
                <thead>
                    <tr>
                        <th class="td-wd">期号</th>
                            <th colspan="2">开奖号码</th>
                            <th>和值</th>
                            <th>跨度</th>
                            <?php for($i=1; $i<7;$i++) :?>
                            <th><?=$i?></th>
                            <?php endfor; ?>
                        </tr>
                </thead>
                <tbody>
                    <?php $a=[1,1,1,1,1,1]; $b=[0,0,0,0,0,0]; $c=[0,0,0,0,0,0]; $d=[0,0,0,0,0,0]; $e=[0,0,0,0,0,0]; $f=[0,0,0,0,0,0]?>
                    <?php foreach ($zst as $key => $value) {  if (!empty($value)){?>
                    <tr>
                        <td class="xcell td-wd">
                            <?=$key < 10 ? '0'.$key : $key?>
                        </td>
                        <td class="xcell td-wd" colspan="2">
                            <?php echo '<span class="red"> ' .$value[0] .' &nbsp;'.$value[1].' &nbsp;'. $value[2] .'</span>'?>
                        </td>
                        <td class="xcell td-wd" >
                            <?=array_sum($value) ?>
                        </td>
                        <td class="xcell td-wd" >
                            <?=max($value) - min($value) ?>
                        </td>
                        <?php for($i=0;$i<6;$i++) : ?>
                        <td class="xcell">
                            <?php if(intval($value[$nkey])==($i+1)) {
                            echo '<i class="'.$color[$nkey].'">'.$value[$nkey].'</i>';
                            $a[$i]=1;
                            $b[$i]++;
                            $f[$i] == 0 ? $f[$i]++ :'';
                            if ($key > 0 && !empty($zst[$key-1][$nkey]) ) {
                                if($zst[$key][$nkey]==$zst[$key-1][$nkey])
                                {
                                    $e[$i]++;
                                    if($e[$i] >= $f[$i])
                                        $f[$i] = $e[$i]+1;
                                } else {
                                    $e[$i] = 0;
                                }
                            }
                        }
                         else {
                            echo $a[$i]++;
                            if($a[$i] > $c[$i])
                                $c[$i] = $a[$i]-1;
                            $d[$i]++;
                            }
                        ?>
                    </td>
                    <?php endfor; ?>
                    </tr>
                    <?php } } ?>
                    <tr class="color-blue" >
                    <td class="xcell td-wd" colspan="5">
                        出现次数
                    </td>
                <?php foreach($b as $val) {?>
                    <td class="xcell" >
                        <?=$val?>
                    </td>
                    <?php }?>
                </tr>
                <tr class="color-black" >
                    <td class="xcell td-wd" colspan="5">
                        平均遗漏
                    </td>
                     <?php foreach($d as $key=>$val) {?>
                    <td class="xcell" >
                        <?=round($d[$key]/($b[$key]+1))?>
                    </td>
                    <?php }?>
                </tr>
                <tr class="color-green" >
                    <td class="xcell td-wd" colspan="5">
                        最大遗漏
                    </td>
                    <?php foreach($c as $val) {?>
                    <td class="xcell" >
                        <?=$val?>
                    </td>
                    <?php }?>
                </tr>
                <tr class="color-theme" >
                    <td class="xcell td-wd" colspan="5">
                        最大连出
                    </td>
                     <?php foreach($f as $val) {?>
                    <td class="xcell" >
                        <?=$val?>
                    </td>
                    <?php }?>
                </tr>
                </tbody>
            </table>
            <canvas id='canvas'></canvas>
        </div>
    </div>

<?php } else if($brid==2) { ?>
    <div class="h-auto trend">
                <div class="table-container">
                    <table class="dataTable">
                        <thead>
                        <tr>
                        <th class="td-wd">期号</th>
                            <th colspan="2">开奖号码</th>
                            <th>和值</th>
                            <th>跨度</th>
                            <?php for($i=1; $i<7;$i++) :?>
                            <th><?=$i?></th>
                            <?php endfor; ?>
                        </tr>
                        </thead>
                        <tbody>
                           <?php $a=[1,1,1,1,1,1]; $b=[0,0,0,0,0,0]; $c=[0,0,0,0,0,0]; $d=[0,0,0,0,0,0]; $e=[0,0,0,0,0,0]; $f=[0,0,0,0,0,0]; $h=$temp1=$temp2=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] ?>
                           <?php foreach ($zst as $key => $value) {  if (!empty($value)){?>
                            <tr>
                                <td class="xcell td-wd">
                                    <?=$key < 10 ? '0'.$key : $key?>
                                </td>
                                <td class="xcell td-wd" colspan="2">
                                    <?php echo '<span class="red"> ' .$value[0] .' &nbsp;'.$value[1].' &nbsp;'. $value[2] .'</span>'?>
                                </td>
                                <td class="xcell td-wd" >
                                    <?=array_sum($value) ?>
                                </td>
                                <td class="xcell td-wd" >
                                    <?=max($value) - min($value) ?>
                                </td>
                                <?php for($i=0;$i<6;$i++) : ?>
                                     <td class="xcell">
                                     <?php
                                            $z = array_sum($value) - 3;
                                            if ($key < 31) {
                                                $h[$z]++;
                                                $temp1[$z]++;
                                                $temp2[$z]++;
                                            }
                                            else if($key<51 && $key >30) {
                                                $h[$z]++;
                                                $temp2[$z]++;
                                            } else {
                                                $h[$z]++;
                                            }
                                                if(intval($value[0])==($i+1) || intval($value[1] == ($i+1)) || intval($value[2] == ($i+1))) {
                                                    $j = $i+1;
                                                    $num = substr_count(implode(',', $value),$j);
                                                    echo $num > 1 ? '<i class="circle-m c-theme">'.$j.'<em class="sign-green">'.$num.'</em></i>' : '<i class="circle-m c-theme">'.$j.'</i>';
                                                    $a[$i]=1;
                                                    $b[$i]++;
                                                    $f[$i] == 0 ? $f[$i]++ :'';
                                                    if ($key > 0 && !empty($zst[$key-1][0]) ) {
                                                        if($j==$zst[$key-1][0] || $j==$zst[$key-1][1] || $j==$zst[$key-1][2])
                                                        {
                                                            $e[$i]++;
                                                            if($e[$i] >= $f[$i])
                                                                $f[$i] = $e[$i]+1;
                                                        } else {
                                                            $e[$i] = 0;
                                                        }
                                                    }
                                                }
                                                 else {
                                                    echo $a[$i]++;
                                                    if($a[$i] > $c[$i])
                                                        $c[$i] = $a[$i]-1;
                                                    $d[$i]++;
                                                    }
                                                ?>
                                                </td>
                                        <?php endfor; ?>
                                    <?php } }?>
                                    <tr class="color-blue">
                            <td class="xcell td-wd " colspan="5">
                                出现次数
                            </td>
                        <?php foreach($b as $val) {?>
                            <td class="xcell">
                                <?=$val?>
                            </td>
                            <?php }?>
                        </tr>
                        <tr class="color-black">
                            <td class="xcell td-wd" colspan="5">
                                平均遗漏
                            </td>
                             <?php foreach($d as $key=>$val) {?>
                            <td class="xcell">
                                <?=round($d[$key]/($b[$key]+1))?>
                            </td>
                            <?php }?>
                        </tr>
                        <tr class="color-green">
                            <td class="xcell td-wd" colspan="5">
                                最大遗漏
                            </td>
                            <?php foreach($c as $val) {?>
                            <td class="xcell">
                                <?=$val?>
                            </td>
                            <?php }?>
                        </tr>
                        <tr class="color-theme">
                            <td class="xcell td-wd" colspan="5">
                                最大连出
                            </td>
                             <?php foreach($f as $val) {?>
                            <td class="xcell">
                                <?=$val?>
                            </td>
                            <?php }?>
                        </tr>
                                </tbody>
                            </table>
                        </div>
            </div>
            <div class="h-auto trend unsee">
                <div class="table-container">
                    <table class="dataTable">
                        <thead>
                            <tr>
                                <th class="td-wd">号码</th>
                                <th colspan="3">30期</th>
                                <th colspan="3">50期</th>
                                <th colspan="3">100期</th>
                                <th colspan="3">遗漏</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php $g=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] ;   ?>
                        <?php for($i=0;$i<16;$i++) { $x=$i+3;?>
                            <tr>
                                <td class="xcell td-wd">
                                    <?=$i < 7 ? '<i class="circle-big c-theme">0'.$x.'</i>' : '<i class="circle-big c-theme">'.$x.'</i>'?>
                                </td>
                                <td class="xcell" colspan="3">
                                    <?php for ($j=0; $j < 30;$j++) {
                                        if (!empty($zst[$j+1])) {
                                            if ( array_sum($zst[$j+1])==$x ) {
                                                $g[$i]++;
                                            }
                                        }
                                    }  echo $g[$i] == max($temp1)/6 ?'<span class="red">'. $g[$i] .'</span>' : $g[$i];?>
                                </td>
                                <td class="xcell" colspan="3">
                                    <?php for ($j=30; $j < 50;$j++) {
                                        if (!empty($zst[$j+1])) {
                                            if ( array_sum($zst[$j+1])==$x ) {
                                                $g[$i]++;
                                            }
                                        }
                                    }  echo $g[$i] == max($h)/6 ?'<span class="red">'. $g[$i] .'</span>' : $g[$i];?>
                                </td>
                                <td class="xcell" colspan="3">
                                    <?php for ($j=50; $j < 100;$j++) {
                                        if (!empty($zst[$j+1])) {
                                            if ( array_sum($zst[$j+1])==$x ) {
                                                $g[$i]++;
                                            }
                                        }
                                    }  echo $g[$i] == max($h)/6 ? '<span class="red">'. $g[$i] .'</span>' : $g[$i];?>
                                </td>
                                <td class="xcell" colspan="3">
                                    <?php echo $h[$i] == min($h) ? '<span class="red">'.(count($zst)-$h[$i]/6).'</span>' : count($zst)-$h[$i]/6; ?>
                                </td>
                            </tr>
                            <?php }?>
                        </tbody>
                    </table>
                </div>
            </div>
<?php } else if ($brid == 3) { ?>
    <div class="h-auto trend">
                <div class="table-container">
                    <table class="dataTable">
                        <thead>
                        <tr>
                        <th class="td-wd">期号</th>
                            <th colspan="2">开奖号码</th>
                            <th>和值</th>
                            <th>跨度</th>
                            <?php for($i=1; $i<7;$i++) :?>
                            <th><?=$i?></th>
                            <?php endfor; ?>
                        </tr>
                        </thead>
                        <tbody>
                           <?php $a=[1,1,1,1,1,1]; $b=[0,0,0,0,0,0]; $c=[0,0,0,0,0,0]; $d=[0,0,0,0,0,0]; $e=[0,0,0,0,0,0]; $f=[0,0,0,0,0,0]; $h=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] ?>
                           <?php foreach ($zst as $key => $value) {  if (!empty($value)){?>
                            <tr>
                                <td class="xcell td-wd">
                                    <?=$key < 10 ? '0'.$key : $key?>
                                </td>
                                <td class="xcell td-wd" colspan="2">
                                    <?php echo '<span class="red"> ' .$value[0] .' &nbsp;'.$value[1].' &nbsp;'. $value[2] .'</span>'?>
                                </td>
                                <td class="xcell td-wd" >
                                    <?=array_sum($value) ?>
                                </td>
                                <td class="xcell td-wd" >
                                     <?=max($value) - min($value) ?>
                                </td>
                                <?php for($i=0;$i<6;$i++) : ?>
                                     <td class="xcell">
                                     <?php
                                                $z = array_sum($value) - 3;
                                                $h[$z]++;
                                                if(intval($value[0])==($i+1) || intval($value[1] == ($i+1)) || intval($value[2] == ($i+1))) {
                                                    $j = $i+1;
                                                    $num = substr_count(implode(',', $value),$j);
                                                    echo $num > 1 ? '<i class="circle-m c-theme">'.$j.'<em class="sign-green">'.$num.'</em></i>' : '<i class="circle-m c-theme">'.$j.'</i>';
                                                    $a[$i]=1;
                                                    $b[$i]++;
                                                    $f[$i] == 0 ? $f[$i]++ :'';
                                                    if ($key > 0 && !empty($zst[$key-1][0]) ) {
                                                        if($j==$zst[$key-1][0] || $j==$zst[$key-1][1] || $j==$zst[$key-1][2])
                                                        {
                                                            $e[$i]++;
                                                            if($e[$i] >= $f[$i])
                                                                $f[$i] = $e[$i]+1;
                                                        } else {
                                                            $e[$i] = 0;
                                                        }
                                                    }
                                                }
                                                 else {
                                                    echo $a[$i]++;
                                                    if($a[$i] > $c[$i])
                                                        $c[$i] = $a[$i]-1;
                                                    $d[$i]++;
                                                    }
                                                ?>
                                                </td>
                                        <?php endfor; ?>
                                    <?php } }?>
                                    <tr class="color-blue">
                            <td class="xcell td-wd " colspan="5">
                                出现次数
                            </td>
                        <?php foreach($b as $val) {?>
                            <td class="xcell">
                                <?=$val?>
                            </td>
                            <?php }?>
                        </tr>
                        <tr class="color-black">
                            <td class="xcell td-wd" colspan="5">
                                平均遗漏
                            </td>
                             <?php foreach($d as $key=>$val) {?>
                            <td class="xcell">
                                <?=round($d[$key]/($b[$key]+1))?>
                            </td>
                            <?php }?>
                        </tr>
                        <tr class="color-green">
                            <td class="xcell td-wd" colspan="5">
                                最大遗漏
                            </td>
                            <?php foreach($c as $val) {?>
                            <td class="xcell">
                                <?=$val?>
                            </td>
                            <?php }?>
                        </tr>
                        <tr class="color-theme">
                            <td class="xcell td-wd" colspan="5">
                                最大连出
                            </td>
                             <?php foreach($f as $val) {?>
                            <td class="xcell">
                                <?=$val?>
                            </td>
                            <?php }?>
                        </tr>
                                </tbody>
                            </table>
                        </div>
            </div>
            <div class="h-auto trend unsee">
                <div class="table-container">
                    <table class="dataTable">
                        <thead>
                            <tr>
                                <th class="td-wd">期号</th>
                                <th class="td-wd">开奖号码</th>
                                <th>三同号</th>
                                <th>三不同</th>
                                <th>二同号</th>
                                <th>二不同</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $a=$b=$c=$d=1; ?>
                            <?php foreach ($zst as $key => $value) {  if (!empty($value)){ $unique = array_unique($value); $num = count($unique); ?>
                             <tr>
                                <td class="xcell td-wd">
                                    <?=$key < 10 ? '0'.$key : $key?>
                                </td>
                                <td class="xcell td-wd" >
                                    <?php echo '<span class="red"> ' .$value[0] .' &nbsp;'.$value[1].' &nbsp;'. $value[2] .'</span>'?>
                                </td>
                                <?php if($num==1) { $b=1;?>
                                <td class="kcell">
                                    <i class="c-dgold">三同号</i>
                                </td>
                                 <td class="kcell">
                                    <?=$a++ ?>
                                </td>
                                <td class="kcell">
                                    <?=$c++ ?>
                                </td>
                                <td class="kcell">
                                    <?=$d++ ?>
                                </td>
                                <?php } else if($num==2) {  ?>
                                <td class="kcell">
                                    <?=$b++ ?>
                                </td>
                                <td class="kcell">
                                    <?=$a++?>
                                </td>
                                <td class="kcell">
                                    <?php $c=1  ?>
                                    <i class="c-lorange">二同号</i>
                                </td>
                                <td class="kcell">
                                    <?php $d=1 ?>
                                    <i class="c-lpurple">二不同</i>
                                </td>
                                <?php } else { ?>
                                <td class="kcell">
                                    <?=$b++ ?>
                                </td>
                                <td class="kcell">
                                    <?php $a=1 ?>
                                    <i class="c-pink">三不同</i>
                                </td>
                                <td class="kcell">
                                    <?=$c++  ?>
                                </td>
                                <td class="kcell">
                                    <?php $d=1 ?>
                                    <i class="c-lpurple">二不同</i>
                                </td>
                                <?php } ?>
                            </tr>
                            <?php } } ?>
                        </tbody>
                    </table>
                </div>
            </div>
<?php } else if($brid==4) { ?>
    <div class="h-auto trend">
                <div class="table-container">
                    <table class="dataTable">
                        <thead>
                        <tr>
                        <th class="td-wd">期号</th>
                            <th colspan="2">开奖号码</th>
                            <th>和值</th>
                            <th>跨度</th>
                            <?php for($i=1; $i<7;$i++) :?>
                            <th><?=$i?></th>
                            <?php endfor; ?>
                        </tr>
                        </thead>
                        <tbody>
                           <?php $a=[1,1,1,1,1,1]; $b=[0,0,0,0,0,0]; $c=[0,0,0,0,0,0]; $d=[0,0,0,0,0,0]; $e=[0,0,0,0,0,0]; $f=[0,0,0,0,0,0]; $h=$temp1=$temp2=[0,0,0,0,0,0]; ?>
                           <?php foreach ($zst as $key => $value) {  if (!empty($value)){?>
                            <tr>
                                <td class="xcell td-wd">
                                    <?=$key < 10 ? '0'.$key : $key?>
                                </td>
                                <td class="xcell td-wd" colspan="2">
                                    <?php echo '<span class="red"> ' .$value[0] .' &nbsp;'.$value[1].' &nbsp;'. $value[2] .'</span>'?>
                                </td>
                                <td class="xcell td-wd" >
                                    <?=array_sum($value) ?>
                                </td>
                                <td class="xcell td-wd" >
                                     <?=max($value) - min($value) ?>
                                </td>
                                <?php for($i=0;$i<6;$i++) : ?>
                                     <td class="xcell">
                                     <?php
                                                $z = $i + 1;
                                                if (in_array($z, $value)) {
                                                    if ($key < 31) {
                                                        $h[$i]++;
                                                        $temp1[$i]++;
                                                        $temp2[$i]++;
                                                    }
                                                    else if($key<51 && $key >30) {
                                                        $h[$i]++;
                                                        $temp2[$i]++;
                                                    } else {
                                                        $h[$i]++;
                                                    }
                                                }
                                                if(intval($value[0])==($i+1) || intval($value[1] == ($i+1)) || intval($value[2] == ($i+1))) {
                                                    $j = $i+1;
                                                    $num = substr_count(implode(',', $value),$j);
                                                    echo $num > 1 ? '<i class="circle-m c-theme">'.$j.'<em class="sign-green">'.$num.'</em></i>' : '<i class="circle-m c-theme">'.$j.'</i>';
                                                    $a[$i]=1;
                                                    $b[$i]++;
                                                    $f[$i] == 0 ? $f[$i]++ :'';
                                                    if ($key > 0 && !empty($zst[$key-1][0]) ) {
                                                        if($j==$zst[$key-1][0] || $j==$zst[$key-1][1] || $j==$zst[$key-1][2])
                                                        {
                                                            $e[$i]++;
                                                            if($e[$i] >= $f[$i])
                                                                $f[$i] = $e[$i]+1;
                                                        } else {
                                                            $e[$i] = 0;
                                                        }
                                                    }
                                                }
                                                 else {
                                                    echo $a[$i]++;
                                                    if($a[$i] > $c[$i])
                                                        $c[$i] = $a[$i]-1;
                                                    $d[$i]++;
                                                    }
                                                ?>
                                                </td>
                                        <?php endfor; ?>
                                    <?php } }?>
                                    <tr class="color-blue">
                            <td class="xcell td-wd " colspan="5">
                                出现次数
                            </td>
                        <?php foreach($b as $val) {?>
                            <td class="xcell">
                                <?=$val?>
                            </td>
                            <?php }?>
                        </tr>
                        <tr class="color-black">
                            <td class="xcell td-wd" colspan="5">
                                平均遗漏
                            </td>
                             <?php foreach($d as $key=>$val) {?>
                            <td class="xcell">
                                <?=round($d[$key]/($b[$key]+1))?>
                            </td>
                            <?php }?>
                        </tr>
                        <tr class="color-green">
                            <td class="xcell td-wd" colspan="5">
                                最大遗漏
                            </td>
                            <?php foreach($c as $val) {?>
                            <td class="xcell">
                                <?=$val?>
                            </td>
                            <?php }?>
                        </tr>
                        <tr class="color-theme">
                            <td class="xcell td-wd" colspan="5">
                                最大连出
                            </td>
                             <?php foreach($f as $val) {?>
                            <td class="xcell">
                                <?=$val?>
                            </td>
                            <?php }?>
                        </tr>
                                </tbody>
                            </table>
                        </div>
            </div>
            <div class="h-auto trend unsee">
                <div class="table-container">
                    <table class="dataTable">
                        <thead>
                            <tr>
                                <th class="td-wd">期号</th>
                                <th class="td-wd">开奖号码</th>
                                <th>三同号</th>
                                <th>三不同</th>
                                <th>二同号</th>
                                <th>二不同</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $a=$b=$c=$d=1; ?>
                            <?php foreach ($zst as $key => $value) {  if (!empty($value)){ $unique = array_unique($value); $num = count($unique); ?>
                             <tr>
                                <td class="xcell td-wd">
                                    <?=$key < 10 ? '0'.$key : $key?>
                                </td>
                                <td class="xcell td-wd" >
                                    <?php echo '<span class="red"> ' .$value[0] .' &nbsp;'.$value[1].' &nbsp;'. $value[2] .'</span>'?>
                                </td>
                                <?php if($num==1) { $b=1;?>
                                <td class="kcell">
                                    <i class="c-dgold">三同号</i>
                                </td>
                                 <td class="kcell">
                                    <?=$a++ ?>
                                </td>
                                <td class="kcell">
                                    <?=$c++ ?>
                                </td>
                                <td class="kcell">
                                    <?=$d++ ?>
                                </td>
                                <?php } else if($num==2) {  ?>
                                <td class="kcell">
                                    <?=$b++ ?>
                                </td>
                                <td class="kcell">
                                    <?=$a++?>
                                </td>
                                <td class="kcell">
                                    <?php $c=1  ?>
                                    <i class="c-lorange">二同号</i>
                                </td>
                                <td class="kcell">
                                    <?php $d=1 ?>
                                    <i class="c-lpurple">二不同</i>
                                </td>
                                <?php } else { ?>
                                <td class="kcell">
                                    <?=$b++ ?>
                                </td>
                                <td class="kcell">
                                    <?php $a=1 ?>
                                    <i class="c-pink">三不同</i>
                                </td>
                                <td class="kcell">
                                    <?=$c++  ?>
                                </td>
                                <td class="kcell">
                                    <?php $d=1 ?>
                                    <i class="c-lpurple">二不同</i>
                                </td>
                                <?php } ?>
                            </tr>
                            <?php } } ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="h-auto trend unsee">
                <div class="table-container">
                    <table class="dataTable">
                        <thead>
                            <tr>
                                <th class="td-wd">号码</th>
                                <th colspan="3">30期</th>
                                <th colspan="3">50期</th>
                                <th colspan="3">100期</th>
                                <th colspan="3">遗漏</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php $g=[0,0,0,0,0,0] ?>
                        <?php for($i=0;$i<6;$i++) { $x=$i+1; ?>
                            <tr>
                                <td class="xcell td-wd">
                                <?='<i class="circle-big c-theme">'.$x.'</i>' ?>
                                </td>
                                <td class="xcell" colspan="3">
                                    <?php for ($j=0; $j < 30;$j++) {
                                        if (!empty($zst[$j+1])) {
                                            if ( in_array($x, $zst[$j+1]) ) {
                                                $g[$i]++;
                                            }
                                        }
                                    }; echo $g[$i] == max($temp1) ? '<span class="red">'. $g[$i] .'</span>' : $g[$i];?>
                                </td>
                                <td class="xcell" colspan="3">
                                    <?php for ($j=30; $j < 51;$j++) {
                                        if (!empty($zst[$j+1])) {
                                            if ( in_array($x, $zst[$j+1]) ) {
                                                $g[$i]++;
                                            }
                                        }
                                    };  echo $g[$i] == max($temp2) ?'<span class="red">'. $g[$i] .'</span>' : $g[$i];?>
                                </td>
                                <td class="xcell" colspan="3">
                                    <?php for ($j=51; $j < 100;$j++) {
                                        if (!empty($zst[$j+1])) {
                                            if ( in_array($x, $zst[$j+1]) ) {
                                                $g[$i]++;
                                            }
                                        }
                                    }  echo $g[$i] == max($h) ?'<span class="red">'. $g[$i] .'</span>' : $g[$i];?>
                                </td>
                                <td class="xcell" colspan="3">
                                    <?php echo $h[$i] == min($h) ? '<span class="red">'.(count($zst)-$h[$i]).'</span>' : count($zst)-$h[$i]; ?>
                                </td>
                            </tr>
                            <?php }?>
                        </tbody>
                    </table>
                </div>
            </div>


<?php } else if($brid==5) { ?>
    <div class="h-auto trend">
                <div class="table-container">
                    <table class="dataTable">
                        <thead>
                        <tr>
                        <th class="td-wd">期号</th>
                            <th colspan="2">开奖号码</th>
                            <th>和值</th>
                            <th>跨度</th>
                            <?php for($i=1; $i<7;$i++) :?>
                            <th><?=$i?></th>
                            <?php endfor; ?>
                        </tr>
                        </thead>
                        <tbody>
                           <?php $a=[1,1,1,1,1,1]; $b=[0,0,0,0,0,0]; $c=[0,0,0,0,0,0]; $d=[0,0,0,0,0,0]; $e=[0,0,0,0,0,0]; $f=[0,0,0,0,0,0]; $h=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] ?>
                           <?php foreach ($zst as $key => $value) {  if (!empty($value)){?>
                            <tr>
                                <td class="xcell td-wd">
                                    <?=$key < 10 ? '0'.$key : $key?>
                                </td>
                                <td class="xcell td-wd" colspan="2">
                                    <?php echo '<span class="red"> ' .$value[0] .' &nbsp;'.$value[1].' &nbsp;'. $value[2] .'</span>'?>
                                </td>
                                <td class="xcell td-wd" >
                                    <?=array_sum($value) ?>
                                </td>
                                <td class="xcell td-wd" >
                                     <?=max($value) - min($value) ?>
                                </td>
                                <?php for($i=0;$i<6;$i++) : ?>
                                     <td class="xcell">
                                     <?php
                                                $z = array_sum($value) - 3;
                                                $h[$z]++;
                                                if(intval($value[0])==($i+1) || intval($value[1] == ($i+1)) || intval($value[2] == ($i+1))) {
                                                    $j = $i+1;
                                                    $num = substr_count(implode(',', $value),$j);
                                                    echo $num > 1 ? '<i class="circle-m c-theme">'.$j.'<em class="sign-green">'.$num.'</em></i>' : '<i class="circle-m c-theme">'.$j.'</i>';
                                                    $a[$i]=1;
                                                    $b[$i]++;
                                                    $f[$i] == 0 ? $f[$i]++ :'';
                                                    if ($key > 0 && !empty($zst[$key-1][0]) ) {
                                                        if($j==$zst[$key-1][0] || $j==$zst[$key-1][1] || $j==$zst[$key-1][2])
                                                        {
                                                            $e[$i]++;
                                                            if($e[$i] >= $f[$i])
                                                                $f[$i] = $e[$i]+1;
                                                        } else {
                                                            $e[$i] = 0;
                                                        }
                                                    }
                                                }
                                                 else {
                                                    echo $a[$i]++;
                                                    if($a[$i] > $c[$i])
                                                        $c[$i] = $a[$i]-1;
                                                    $d[$i]++;
                                                    }
                                                ?>
                                                </td>
                                        <?php endfor; ?>
                                    <?php } }?>
                                    <tr class="color-blue">
                            <td class="xcell td-wd " colspan="5">
                                出现次数
                            </td>
                        <?php foreach($b as $val) {?>
                            <td class="xcell">
                                <?=$val?>
                            </td>
                            <?php }?>
                        </tr>
                        <tr class="color-black">
                            <td class="xcell td-wd" colspan="5">
                                平均遗漏
                            </td>
                             <?php foreach($d as $key=>$val) {?>
                            <td class="xcell">
                                <?=round($d[$key]/($b[$key]+1))?>
                            </td>
                            <?php }?>
                        </tr>
                        <tr class="color-green">
                            <td class="xcell td-wd" colspan="5">
                                最大遗漏
                            </td>
                            <?php foreach($c as $val) {?>
                            <td class="xcell">
                                <?=$val?>
                            </td>
                            <?php }?>
                        </tr>
                        <tr class="color-theme">
                            <td class="xcell td-wd" colspan="5">
                                最大连出
                            </td>
                             <?php foreach($f as $val) {?>
                            <td class="xcell">
                                <?=$val?>
                            </td>
                            <?php }?>
                        </tr>
                                </tbody>
                            </table>
                        </div>
            </div>
            <div class="h-auto trend unsee">
                <div class="table-container">
                    <table class="dataTable">
                        <thead>
                            <tr>
                                <th class="td-wd">期号</th>
                                <th colspan="2">开奖号码</th>
                                <?php for($i=1;$i<7;$i++){ ?>
                                <th><?=$i.$i?></th>
                              <?php }?>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $a=[0,0,0,0,0,0]; ?>
                            <?php foreach ($zst as $key => $value) {  if (!empty($value)){ $unique = array_unique($value); $num = count($unique); $suan = array_diff_assoc( $value, $unique); ?>
                             <tr>
                                <td class="xcell td-wd">
                                    <?=$key < 10 ? '0'.$key : $key?>
                                </td>
                                <td class="xcell td-wd" colspan="2">
                                    <?php echo '<span class="red"> ' .$value[0] .' &nbsp;'.$value[1].' &nbsp;'. $value[2] .'</span>'?>
                                </td>
                                <?php for($j=0;$j<6;$j++) {
                                    $x = $j+1;
                                    if(current($suan) == ($x)) {
                                        $a[$j] = 0;
                                        echo '<td class="kcell"><i class="c-dgold">'.$x.$x.'</i> </td>';
                                    }
                                    else {
                                        $a[$j]++;
                                        echo '<td class="kcell">'.$a[$j].'</td>';
                                    }
                               }
                               ?>
                        </tr>
                            <?php }} ?>
                        </tbody>
                    </table>
                </div>
            </div>
<?php } else if($brid==6) { ?>
    <div class="h-auto trend">
                <div class="table-container">
                    <table class="dataTable">
                        <thead>
                        <tr>
                        <th class="td-wd">期号</th>
                            <th colspan="2">开奖号码</th>
                            <th>和值</th>
                            <th>跨度</th>
                            <?php for($i=1; $i<7;$i++) :?>
                            <th><?=$i?></th>
                            <?php endfor; ?>
                        </tr>
                        </thead>
                        <tbody>
                           <?php $a=[1,1,1,1,1,1]; $b=[0,0,0,0,0,0]; $c=[0,0,0,0,0,0]; $d=[0,0,0,0,0,0]; $e=[0,0,0,0,0,0]; $f=[0,0,0,0,0,0]; $h=$temp1=$temp2=[0,0,0,0,0,0] ?>
                           <?php foreach ($zst as $key => $value) {  if (!empty($value)){?>
                            <tr>
                                <td class="xcell td-wd">
                                    <?=$key < 10 ? '0'.$key : $key?>
                                </td>
                                <td class="xcell td-wd" colspan="2">
                                    <?php echo '<span class="red"> ' .$value[0] .' &nbsp;'.$value[1].' &nbsp;'. $value[2] .'</span>'?>
                                </td>
                                <td class="xcell td-wd" >
                                    <?=array_sum($value) ?>
                                </td>
                                <td class="xcell td-wd" >
                                     <?=max($value) - min($value) ?>
                                </td>
                                <?php for($i=0;$i<6;$i++) : ?>
                                     <td class="xcell">
                                     <?php
                                                $z = $i + 1;
                                                if (in_array($z, $value)) {
                                                    if ($key < 31) {
                                                        $h[$i]++;
                                                        $temp1[$i]++;
                                                        $temp2[$i]++;
                                                    }
                                                    else if($key<51 && $key >30) {
                                                        $h[$i]++;
                                                        $temp2[$i]++;
                                                    } else {
                                                        $h[$i]++;
                                                    }
                                                }
                                                if(intval($value[0])==($i+1) || intval($value[1] == ($i+1)) || intval($value[2] == ($i+1))) {
                                                    $j = $i+1;
                                                    $num = substr_count(implode(',', $value),$j);
                                                    echo $num > 1 ? '<i class="circle-m c-theme">'.$j.'<em class="sign-green">'.$num.'</em></i>' : '<i class="circle-m c-theme">'.$j.'</i>';
                                                    $a[$i]=1;
                                                    $b[$i]++;
                                                    $f[$i] == 0 ? $f[$i]++ :'';
                                                    if ($key > 0 && !empty($zst[$key-1][0]) ) {
                                                        if($j==$zst[$key-1][0] || $j==$zst[$key-1][1] || $j==$zst[$key-1][2])
                                                        {
                                                            $e[$i]++;
                                                            if($e[$i] >= $f[$i])
                                                                $f[$i] = $e[$i]+1;
                                                        } else {
                                                            $e[$i] = 0;
                                                        }
                                                    }
                                                }
                                                 else {
                                                    echo $a[$i]++;
                                                    if($a[$i] > $c[$i])
                                                        $c[$i] = $a[$i]-1;
                                                    $d[$i]++;
                                                    }
                                                ?>
                                                </td>
                                        <?php endfor; ?>
                                    <?php } }?>
                                    <tr class="color-blue">
                            <td class="xcell td-wd " colspan="5">
                                出现次数
                            </td>
                        <?php foreach($b as $val) {?>
                            <td class="xcell">
                                <?=$val?>
                            </td>
                            <?php }?>
                        </tr>
                        <tr class="color-black">
                            <td class="xcell td-wd" colspan="5">
                                平均遗漏
                            </td>
                             <?php foreach($d as $key=>$val) {?>
                            <td class="xcell">
                                <?=round($d[$key]/($b[$key]+1))?>
                            </td>
                            <?php }?>
                        </tr>
                        <tr class="color-green">
                            <td class="xcell td-wd" colspan="5">
                                最大遗漏
                            </td>
                            <?php foreach($c as $val) {?>
                            <td class="xcell">
                                <?=$val?>
                            </td>
                            <?php }?>
                        </tr>
                        <tr class="color-theme">
                            <td class="xcell td-wd" colspan="5">
                                最大连出
                            </td>
                             <?php foreach($f as $val) {?>
                            <td class="xcell">
                                <?=$val?>
                            </td>
                            <?php }?>
                        </tr>
                                </tbody>
                            </table>
                        </div>
            </div>
            <div class="h-auto trend unsee">
                <div class="table-container">
                    <table class="dataTable">
                        <thead>
                            <tr>
                                <th class="td-wd">号码</th>
                                <th colspan="3">30期</th>
                                <th colspan="3">50期</th>
                                <th colspan="3">100期</th>
                                <th colspan="3">遗漏</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php $g=[0,0,0,0,0,0] ?>
                        <?php for($i=0;$i<6;$i++) { $x=$i+1; ?>
                            <tr>
                                <td class="xcell td-wd">
                                <?='<i class="circle-big c-theme">'.$x.'</i>' ?>
                                </td>
                                <td class="xcell" colspan="3">
                                    <?php for ($j=0; $j < 31;$j++) {
                                        if (!empty($zst[$j+1])) {
                                            if ( in_array($x, $zst[$j+1]) ) {
                                                $g[$i]++;
                                            }
                                        }
                                    }  echo $g[$i] == max($temp1) ?'<span class="red">'. $g[$i] .'</span>' : $g[$i];?>
                                </td>
                                <td class="xcell" colspan="3">
                                    <?php for ($j=31; $j < 51;$j++) {
                                        if (!empty($zst[$j+1])) {
                                            if ( in_array($x, $zst[$j+1]) ) {
                                                $g[$i]++;
                                            }
                                        }
                                    }  echo $g[$i] == max($temp2) ?'<span class="red">'. $g[$i] .'</span>' : $g[$i];?>
                                </td>
                                <td class="xcell" colspan="3">
                                    <?php for ($j=51; $j < 100;$j++) {
                                        if (!empty($zst[$j+1])) {
                                            if ( in_array($x, $zst[$j+1]) ) {
                                                $g[$i]++;
                                            }
                                        }
                                    }  echo $g[$i] == max($h) ?'<span class="red">'. $g[$i] .'</span>' : $g[$i];?>
                                </td>
                                <td class="xcell" colspan="3">
                                    <?php echo $h[$i] == min($h) ? '<span class="red">'.(count($zst)-$h[$i]).'</span>' : count($zst)-$h[$i]; ?>
                                </td>
                            </tr>
                            <?php }?>
                        </tbody>
                    </table>
                </div>
            </div>

<?php } else if($brid==7) { ?>
    <div class="h-auto trend">
                <div class="table-container">
                    <table class="dataTable">
                        <thead>
                        <tr>
                        <th class="td-wd">期号</th>
                            <th colspan="2">开奖号码</th>
                            <th>和值</th>
                            <th>跨度</th>
                            <?php for($i=1; $i<7;$i++) :?>
                            <th><?=$i?></th>
                            <?php endfor; ?>
                        </tr>
                        </thead>
                        <tbody>
                           <?php $a=[1,1,1,1,1,1]; $b=[0,0,0,0,0,0]; $c=[0,0,0,0,0,0]; $d=[0,0,0,0,0,0]; $e=[0,0,0,0,0,0]; $f=[0,0,0,0,0,0]; $h=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] ?>
                           <?php foreach ($zst as $key => $value) {  if (!empty($value)){?>
                            <tr>
                                <td class="xcell td-wd">
                                    <?=$key < 10 ? '0'.$key : $key?>
                                </td>
                                <td class="xcell td-wd" colspan="2">
                                    <?php echo '<span class="red"> ' .$value[0] .' &nbsp;'.$value[1].' &nbsp;'. $value[2] .'</span>'?>
                                </td>
                                <td class="xcell td-wd" >
                                    <?=array_sum($value) ?>
                                </td>
                                <td class="xcell td-wd" >
                                     <?=max($value) - min($value) ?>
                                </td>
                                <?php for($i=0;$i<6;$i++) : ?>
                                     <td class="xcell">
                                     <?php
                                                $z = array_sum($value) - 3;
                                                $h[$z]++;
                                                if(intval($value[0])==($i+1) || intval($value[1] == ($i+1)) || intval($value[2] == ($i+1))) {
                                                    $j = $i+1;
                                                    $num = substr_count(implode(',', $value),$j);
                                                    echo $num > 1 ? '<i class="circle-m c-theme">'.$j.'<em class="sign-green">'.$num.'</em></i>' : '<i class="circle-m c-theme">'.$j.'</i>';
                                                    $a[$i]=1;
                                                    $b[$i]++;
                                                    $f[$i] == 0 ? $f[$i]++ :'';
                                                    if ($key > 0 && !empty($zst[$key-1][0]) ) {
                                                        if($j==$zst[$key-1][0] || $j==$zst[$key-1][1] || $j==$zst[$key-1][2])
                                                        {
                                                            $e[$i]++;
                                                            if($e[$i] >= $f[$i])
                                                                $f[$i] = $e[$i]+1;
                                                        } else {
                                                            $e[$i] = 0;
                                                        }
                                                    }
                                                }
                                                 else {
                                                    echo $a[$i]++;
                                                    if($a[$i] > $c[$i])
                                                        $c[$i] = $a[$i]-1;
                                                    $d[$i]++;
                                                    }
                                                ?>
                                                </td>
                                        <?php endfor; ?>
                                    <?php } }?>
                                    <tr class="color-blue">
                            <td class="xcell td-wd " colspan="5">
                                出现次数
                            </td>
                        <?php foreach($b as $val) {?>
                            <td class="xcell">
                                <?=$val?>
                            </td>
                            <?php }?>
                        </tr>
                        <tr class="color-black">
                            <td class="xcell td-wd" colspan="5">
                                平均遗漏
                            </td>
                             <?php foreach($d as $key=>$val) {?>
                            <td class="xcell">
                                <?=round($d[$key]/($b[$key]+1))?>
                            </td>
                            <?php }?>
                        </tr>
                        <tr class="color-green">
                            <td class="xcell td-wd" colspan="5">
                                最大遗漏
                            </td>
                            <?php foreach($c as $val) {?>
                            <td class="xcell">
                                <?=$val?>
                            </td>
                            <?php }?>
                        </tr>
                        <tr class="color-theme">
                            <td class="xcell td-wd" colspan="5">
                                最大连出
                            </td>
                             <?php foreach($f as $val) {?>
                            <td class="xcell">
                                <?=$val?>
                            </td>
                            <?php }?>
                        </tr>
                                </tbody>
                            </table>
                        </div>
            </div>
<?php } ?>

