<?php
    $bet = $js = $betdate = $js2 = $js3 = $js4 = $js5 = '';
    if (isset($_GET['limit'])) {
        $urlLimit = $_GET['limit'];
        $js = '$("#limit").val('.$urlLimit.');';
        if (!in_array($_GET['limit'], $perpage))
            $urlLimit = current($perpage);
    }
    if (!empty($_GET['page'])) {
        if (is_numeric($_GET['page'])) {
            $js4 = '$("#page").val('.$_GET['page'].');';
            $page = $_GET['page'];
        }
        else {
            $js4 = '$("#page").val(1);';
            $page =1;
        }
    }
    if(!empty($type)) {
        if (isset($_GET['type']) && $_GET['type'] !=0) {
            $js= '$("#bet_type").val('.$_GET['type'].');';
            if (!empty($type))
                $bet = $type[$_GET['type']];
        } else
            $bet = current($type);
    }

    if(!empty($date)) {
        if (isset($_GET['date'])) {
            $js2= '$("#date").val('.$_GET['date'].');';
            if (!empty($date))
                $betdate = $_GET['date'];
        } else
            $betdate = current($date);
    }
?>
<div class="chart-query-body container">
        <div class="top-title">
            <i class="financail-red"></i> <em class="tit">报表查询</em>
        </div>
   
        <div class="search-box">
            <div class="search-down">彩票类型:
                <div class="select-box">
                    <select class="list" name = "type" id="bet_type">
                    <?php if(!empty($bet)) : foreach ($type as $key => $value) : ?>
                        <option value="<?=$key?>"><em class="txt"><?=$value?></em></option>
                    <?php endforeach; endif;?>
                    </select>
                    <em class="txt"><?=$bet?></em>
                    <i class="i-arrow"></i>
                </div>
            </div>
        <?php if(!empty($issue)){?>
            <div class="" id='issue'>
            当前期数:
            <div class="select-box">
                <select class="list" id='serial'>
                <?php  if(!empty($date)) :  foreach ($date as $key=>$value): ?>
                    <option value="<?=$value?>"><?=$value?></option>
                <?php endforeach; endif;?>
                </select>
                <em class="txt" id="issueNum"><?=!empty($issue) ? $issue : '期'?></em>
                <i class="i-arrow"></i>
            </div>
            <!--<button class="search-btn" id="sub">查询</button>-->
            </div>
        <?php }?>
        </div>
        <?php
            
            $v2 = $v3 =$v4 =$v5 =$v6 = '';
            $v1 = 'on';
            
            if(isset($_GET['pame']))
            {
                $pame = $_GET['pame'];
                $on = $_GET['pame'];
                if($on ==1) {
                    $v1 = 'on';
                }
                if($on ==2) {
                    $v2 = 'on';
                    $v1 = '';
                }
                if($on ==3) {
                    $v3 = 'on';
                    $v1 = '';
                }
                if($on ==4) {
                    $v4 = 'on';
                    $v1 = '';
                }
                if($on ==5) {
                    $v5 = 'on';
                    $v1 = '';
                }
                if($on ==6) {
                    $v6 = 'on';
                    $v1 = '';
                }
            }
        ?>
         <div class="search-box">
            <span class="quik-btn <?=$v2?>" data-id=2 >昨日</span>
            <span class="quik-btn <?=$v1?>" data-id=1 >今日</span>
            <span class="quik-btn <?=$v3?>" data-id=3 >本周</span>
            <span class="quik-btn <?=$v4?>" data-id=4 >上周</span>
            <span class="quik-btn <?=$v5?>" data-id=5 >本月</span>
            <span class="quik-btn <?=$v6?>" data-id=6 >上月</span>
            <a class="output-chart" id="excel" href="javascript:">导出报表</a>
            <?php echo date('Y-m-d',$start) ?>&nbsp至&nbsp<?php echo date('Y-m-d',$end) ?>
        </div>
        <div class="table-box">
            <table class="main-table" cellpadding="0" cellspacing="0">
                <thead>
                    <tr>
                        <th>用户名</th>
                        <th>类型</th>
                        <th>下级投注</th>
                        <th>下级派彩</th>                      
                        <th>下级回水</th>
                        <th>下级贡献</th>
                        <th>下级返点</th>
                        <th>本级佣金</th>   
                        <th>本级投注</th>
                        <th>本级派彩</th>
                        <th>本级回水</th>
                        <th>本级输赢</th>
                        
                        <th>本级订单详情</th>   
                    </tr>
                </thead>
                <tbody>
                <?php if (empty($info['total'])) {?>
                   <tr class="null">
                        <td colspan="13">暂无数据！</td>
                    </tr>
                    <?php } else { foreach ($info['list'] as $key=>$value) : ?>
                    <tr id="next">
                    
                        <?php if(empty($issue)){ ?>
                            <td><a class="operate" href="<?=$value['u_type'] == 3?'/forms/total?v=2&&type='.$betId.'&&pame='.$pame.'&&uid='.$value['u_id']:'/forms/total?v=4&&type='.$betId.'&&pame='.$pame.'&&uid='.$value['u_id'] ?>"><?=$value['u_name']?></a></td>
                        <?php }else{ ?>
                            <td><a class="operate" href="<?=$value['u_type'] == 3?'/forms/total?v=2&&type='.$betId.'&&pame='.$pame.'&&issue='.$issue.'&&uid='.$value['u_id']:'/forms/total?v=4&&type='.$betId.'&&pame='.$pame.'&&issue='.$issue.'&&uid='.$value['u_id'] ?>"><?=$value['u_name']?></a></td>
                        <?php } ?>
                        <td><?=$value['u_type'] == 3?'代理':'会员' ?></td>
                        <td><?=intval($value['pfr_team_bet_money'])!==0?sprintf("%.2f", $value['pfr_team_bet_money']):'-' ?></td>
                        <td><?=intval($value['pfr_team_earn_money'])!==0?sprintf("%.2f",$value['pfr_team_earn_money']):'-' ?></td>
                        <td><?=intval($value['pfr_team_reback_money'])!==0?sprintf("%.2f",$value['pfr_team_reback_money']):'-' ?></td>
                        <td><?=intval($value['pfr_team_plat_money'])!==0?sprintf("%.2f",$value['pfr_team_plat_money']):'-' ?></td>
                        <td><?=intval($value['pfr_team_back_money']-$value['pfr_my_back_money'])!==0?sprintf("%.2f",($value['pfr_team_back_money']-$value['pfr_my_back_money'])):'-'?></td>
                        <td><?=intval($value['pfr_my_back_money'])!==0?sprintf("%.2f",$value['pfr_my_back_money']):'-' ?></td>
                        <td><?=intval($value['pfr_my_bet_money'])!==0?sprintf("%.2f",$value['pfr_my_bet_money']):'-' ?></td>
                        <td><?=intval($value['pfr_my_earn_money'])!==0?sprintf("%.2f",$value['pfr_my_earn_money']):'-' ?></td>
                        <td><?=intval($value['pfr_my_reback_money'])!==0?sprintf("%.2f",$value['pfr_my_reback_money']):'-' ?></td>
                        <td><?=intval($value['pfr_my_earn_money'] + $value['pfr_my_reback_money'] - $value['pfr_my_bet_money'])!==0?sprintf("%.2f",($value['pfr_my_earn_money'] + $value['pfr_my_reback_money'] - $value['pfr_my_bet_money'])):'-'?></td>
                        
                        <td><a class="operate" href="<?='/forms/total?v=4&&type='.$betId.'&&pame='.$pame.'&&issue='.$issue.'&&uid='.$value['u_id'] ?>">订单详情</a></td>

                    </tr>
                       <?php  endforeach;  ?>
                </tbody>
            </table>
        </div>

        <div class="pages">
            <div class="posl">
                共<em class="counts" ><?=$info['total']?></em>条 每页显示
                <div class="select-box line-num">
                    <select class="list" id="limit">
                    <?php foreach ($perpage as $key => $value) : ?>
                        <?php if(!empty($urlLimit)){ ?>
                            <option value="<?=$key?>" <?=$urlLimit == $value ? 'selected="selected"' : ''?> ><?=$value?></option>
                        <?php }else{?>
                            <option value="<?=$key?>" ><?=$value?></option>
                        <?php }?>
                    <?php endforeach ?>
                    </select>
                    <em class="txt"><?=!empty($urlLimit) ? $urlLimit : current($perpage); ?></em>
                    <i class="i-arrow"></i>
                </div>条
            </div>
            <div class="switch-box">
                <a class="page-btn mr10" id="left"><i class="left"></i></a> 第
                <div class="select-box line-num">
                    <select class="list" id="page">
                      <?php if(!empty($info['limit'])): for($i=1; $i <= $info['limit']; $i++ ) : ?>
                        <option value="<?=$i?>"><?=$i?></option>
                    <?php endfor; endif; ?>
                    </select>
                    <em class="txt"><?=!empty($page) ? $page: 1?></em>
                    <i class="i-arrow"></i>
                </div>
                共<em id="total"><?=$info['limit']?></em>页
                <a class="page-btn ml10" id="right"><i class="right" ></i></a>
            </div>
        </div>
    <?php }?>
    </div>

<script type="text/javascript">
    <?php echo $js; echo $js2; echo $js3; echo $js4;?>
    var dateId = '';
    $(function() {
        $('#bet_type').on('change', function(){
           var bid = $('#bet_type').val();
            if(dateId == '')
            {
                dateId = <?php echo !empty($_GET['pame'])?$_GET['pame']:1 ?>;
            }
            var url = '/forms/total?v=1&&type='+bid+'&&pame='+dateId;
            location.href = url;
        });

        function getUrlParam(name) {
          var reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)"); //构造一个含有目标参数的正则表达式对象
          var r = window.location.search.substr(1).match(reg); //匹配目标参数
          if (r != null) return unescape(r[2]);
          return null; //返回参数值
        }

        $('#excel').on('click',function(){
            if ($("#bet_type").val())
                var type = $("#bet_type").val();
            else
                var type = 0;
            var pame = getUrlParam('pame');
            var uid = getUrlParam('uid');
            var issue = $('#issueNum').html();
            if(issue == null )
            {
                issue = '';
            }
            if (getUrlParam('uid') == null)
                uid = 0;
            var url = '/forms/excel?v=2&&type='+type+'&&pame='+pame+'&&uid='+uid+'&&issue='+issue;
            location.href = url;
    });
    
    $('.quik-btn').on('click',function(){
        dateId = $(this).data('id');
        var betId = $("#bet_type").val();
        var url = '/forms/total?v=1&&type='+betId+'&&pame='+dateId;
        location.href = url;
    });
});
</script>