<?php
    $bet = $js = $betdate = $js2 = $js3 = $js4 = $js5 = '';
    if (isset($_GET['limit'])) {
        $urlLimit = $_GET['limit'];
        $js = '$("#limit").val('.$urlLimit.');';
        if (!in_array($_GET['limit'], $perpage))
            $urlLimit = current($perpage);
    }
    if (!empty($_GET['page'])) {
        if (is_numeric($_GET['page'])) {
            $js4 = '$("#page").val('.$_GET['page'].');';
            $page = $_GET['page'];
        }
        else {
            $js4 = '$("#page").val(1);';
            $page =1;
        }
    }
    if(!empty($type)) {
        if (isset($_GET['type']) && $_GET['type'] !=0) {
            $js= '$("#bet_type").val('.$_GET['type'].');';
            if (!empty($type))
                $bet = $type[$_GET['type']];
        } else
            $bet = current($type);
    }

    if(!empty($date)) {
        if (isset($_GET['date'])) {
            $js2= '$("#date").val('.$_GET['date'].');';
            if (!empty($date))
                $betdate = $_GET['date'];
        } else
            $betdate = current($date);
    }
?>

<div class="chart-query-body container">
        <div class="top-title">
            <i class="financail-red"></i> <em class="tit">报表查询</em>
        </div>
        <div class="search-box">
            <div class="search-down">彩票类型:
                <div class="select-box">
                    <select class="list" name = "type" id="bet_type">
                        
                    <?php if(!empty($type)) : foreach ($type as $key => $value) : ?>
                        <option value="<?=$key?>"><em class="txt"><?=$value?></em></option>
                    <?php endforeach; endif;?>
                    </select>
                    <em class="txt"><?=$bet?></em>
                    <i class="i-arrow"></i>
                </div>
            </div>
        <?php if(empty($issue)){ ?>
        <div class="" id='issue'>
        按期查询:
        <div class="select-box">
            <select class="list" id='serial'>
                <option value=""><em class="txt">请选择期</em></option>
            <?php  if(!empty($date)) :  foreach ($date as $key=>$value): ?>
                <option value="<?=$value?>"><?=$value?></option>
            <?php endforeach; endif;?>
            </select>
            <em class="txt" id="issueNum"><?=!empty($date[0]) ? $date[0] : '期'?></em>
            <i class="i-arrow"></i>
        </div>
        <?php }else{ ?>
        <div class="" id='issue'>
        按期查询:
        <div class="select-box">
            <select class="list" id='serial'>
            <?php  if(!empty($date)) :  foreach ($date as $key=>$value): ?>
                <option value="<?=$value?>"><?=$value?></option>
            <?php endforeach; endif;?>
            </select>
            <em class="txt" id="issueNum"><?=!empty($issue) ? $issue : '期'?></em>
            <i class="i-arrow"></i>
        </div>
        <?php } ?>
        </div>
        <?php
             if(isset($_GET['v']))
                $v = $_GET['v']+1;
             else
                $v = 2;

            $v2 = $v3 =$v4 =$v5 =$v6 = '';
            $v1 = 'on';

            if(isset($_GET['pame']))
            {
                $pame = $_GET['pame'];
                $on = $_GET['pame'];
                if($on ==1) {
                    $v1 = 'on';
                }
                if($on ==2) {
                    $v2 = 'on';
                    $v1 = '';
                }
                if($on ==3) {
                    $v3 = 'on';
                    $v1 = '';
                }
                if($on ==4) {
                    $v4 = 'on';
                    $v1 = '';
                }
                if($on ==5) {
                    $v5 = 'on';
                    $v1 = '';
                }
                if($on ==6) {
                    $v6 = 'on';
                    $v1 = '';
                }
            } else
                $pame = 1;
        ?>
        
         <div class="search-box">
            <span class="quik-btn <?=$v2?>" data-id=2 >昨日</span>
            <span class="quik-btn <?=$v1?>" data-id=1 >今日</span>
            <span class="quik-btn <?=$v3?>" data-id=3 >本周</span>
            <span class="quik-btn <?=$v4?>" data-id=4 >上周</span>
            <span class="quik-btn <?=$v5?>" data-id=5 >本月</span>
            <span class="quik-btn <?=$v6?>" data-id=6 >上月</span>
            <a class="output-chart" id="excel" href="javascript:">导出报表</a>
            <?php echo date('Y-m-d',$start) ?>&nbsp至&nbsp<?php echo date('Y-m-d',$end) ?>
        </div>
        <div class="table-box">
            <table class="main-table" cellpadding="0" cellspacing="0">
                <thead>
                    <tr>
                        <th>彩种</th>
                        <th>日期</th>
                        <th>期号</th>
                        <th>投注数</th>
                        <th>投注金额</th>
                        <th>派彩金额</th>
                        <th>代理总返点金额</th>
                        <th>盈亏</th>
                    </tr>
                </thead>
                <tbody>
                <?php if (empty($info['total'])) {?>
                   <tr class="null">
                        <td colspan="10">暂无数据！</td>
                    </tr>
                    <?php } else { foreach ($info['list'] as $value) : $date = '';
                    if ($v==3 && !empty($value['bt_date']))
                        $date = '&&date='.$value['bt_date'];
                    if ($v==4 && !empty($value['bt_periods']))
                        $date = '&&date='.$value['bt_periods']; ?>
                    <tr>
                    <?php if($v < 5) {?>
                        <?php if(empty($issue)){ ?>
                            <?php if($value['bet_id']==0){ ?>
                                <td><?=$type[$value['bet_id']]?></td>
                            <?php }else{ ?>
                                <td><a class="operate" href = /forms/total?v=<?=$v?>&&type=<?=$value['bet_id']?>&&pame=<?=$pame?><?=$date?>><?=$type[$value['bet_id']]?></a></td>
                            <?php } ?>
                        <?php }else{ ?>
                            <?php if($value['bet_id']==0){ ?>
                                <td><?=$type[$value['bet_id']]?></td>
                            <?php }else{ ?>
                                <td><a class="operate" href = /forms/total?v=<?=$v?>&&type=<?=$value['bet_id']?>&&pame=<?=$pame?>&&issue=<?=$issue?>><?=$type[$value['bet_id']]?></a></td>
                            <?php } ?> 
                        <?php } ?>
                    <?php }else { ?>
                        <td><?=$type[$value['bet_id']]?></td>
                        <?php } ?>
                        <td><?php echo !empty($value['bt_date']) ? date('Y-m-d',$value['bt_date']) : '-'?></td>
                        <td><?php echo !empty($value['bt_periods']) ? $value['bt_periods'] : '-'?></td>
                        <td><?php echo !empty($value['bt_all_orders']) ? $value['bt_all_orders']:0?></td>
                        <td><?=!empty($value['bt_all_in'])?sprintf("%.2f",$value['bt_all_in']):0?></td>
                        <td><?=!empty($value['bt_all_out'])?sprintf("%.2f",$value['bt_all_out']):0?></td>
                        <td><?=!empty($value['bt_all_reback'])?sprintf("%.2f",$value['bt_all_reback']):0?></td>
                        <td><?=!empty($value['bt_all_earn'])?sprintf("%.2f",$value['bt_all_earn']):0?></td>
                    </tr>
                       <?php  endforeach;  ?>
                    <tr>
                        <td>总计</td>
                        <td>-</td>
                        <td>-</td>
                        <td><?=$info['num']?></td>
                        <td><?=sprintf("%.2f",$info['bet'])?></td>
                        <td><?=sprintf("%.2f",$info['bonus'])?></td>
                        <td><?=sprintf("%.2f",$info['back'])?></td>
                        <td><?=!empty($info['earn'])?sprintf("%.2f",$info['earn']):0?></td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="pages">
            <div class="posl">
                共<em class="counts" ><?=$info['total']?></em>条 每页显示
                <div class="select-box line-num">
                    <select class="list" id="limit">
                    <?php foreach ($perpage as $key => $value) : ?>
                        <option value="<?=$key?>"><?=$value?></option>
                    <?php endforeach ?>
                    </select>
                    <em class="txt"><?=!empty($urlLimit) ? $urlLimit : current($perpage); ?></em>
                    <i class="i-arrow"></i>
                </div>条
            </div>
            <div class="switch-box">
                <a class="page-btn mr10" id="left"><i class="left"></i></a> 第
                <div class="select-box line-num">
                    <select class="list" id="page">
                      <?php if(!empty($info['limit'])): for($i=1; $i <= $info['limit']; $i++ ) : ?>
                        <option value="<?=$i?>"><?=$i?></option>
                    <?php endfor; endif; ?>
                    </select>
                    <em class="txt"><?=!empty($page) ? $page: 1?></em>
                    <i class="i-arrow"></i>
                </div>
                共<em id="total"><?=$info['limit']?></em>页
                <a class="page-btn ml10" id="right"><i class="right" ></i></a>
            </div>
        </div>
        <input type="hidden" id='date' value=<?php echo !empty($info['list'][0]['bt_date']) ? $info['list'][0]['bt_date'] : '' ?>>
        <input type="hidden" id='per' value=<?php echo !empty($info['list'][0]['bt_periods']) ? $info['list'][0]['bt_periods'] : '' ?>>
    <?php }?>
    </div>

<script type="text/javascript">


    <?php echo $js; echo $js2; echo $js3; echo $js4;?>
   $(function() {
        var bid = $('#bet_type').val();
        if(bid!=='0')
        {
            $('#issue').removeClass('unsee');
        }
        $('#ifIssue').click(function(){
            $(this).toggle().attr('checked');
        })
        $('#bet_type').on('change', function(){
            var bid = $('#bet_type').val();
            
            var url = '/forms/total?type='+bid;
            location.href = url;
        });
        $('#serial').change(function(){
            var issue = $('#serial').val();
            var url = '/forms/total?type='+bid+'&&issue='+issue;
            location.href = url;
        })
        function getUrlParam(name) {
          var reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)"); //构造一个含有目标参数的正则表达式对象
          var r = window.location.search.substr(1).match(reg); //匹配目标参数
          if (r != null) return unescape(r[2]);
          return null; //返回参数值
        }

        $('#excel').on('click',function(){
            if ($("#bet_type").val())
                var type = $("#bet_type").val();
            else
                var type = 0; 
            var pame = getUrlParam('pame');
            if(pame == null )
            {
                pame = 1;
            }
            var v = getUrlParam('v');
            var issue = $('#issueNum').html();
            if(issue == null )
            {
                issue = '';
            }
            if(type == 0)
            {
                issue = '';
            }
            if (getUrlParam('v') == null)
                v = 1;
            var url = '/forms/excel?v='+v+'&&type='+type+'&&pame='+pame+'&&issue='+issue;
            location.href = url;
    })

    $('.quik-btn').on('click',function(){
        var id = $(this).data('id');
        var v = getUrlParam('v');
        if (getUrlParam('v') == null)
            v = 1;
        if (v > 2)
            v = 2;

        if ($("#bet_type").val())
                var type = $("#bet_type").val();
        else
                var type = 0;
        var url = '/forms/total?v='+v+'&&type='+type+'&&pame='+id;
        location.href = url;
    })
})
</script>